// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/data/data.proto

package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeDetail struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName             string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal               float64  `protobuf:"fixed64,5,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal               float64  `protobuf:"fixed64,6,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	Mq                   []*MQ    `protobuf:"bytes,7,rep,name=mq,proto3" json:"mq,omitempty"`
	Active               bool     `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDetail) Reset()         { *m = NodeDetail{} }
func (m *NodeDetail) String() string { return proto.CompactTextString(m) }
func (*NodeDetail) ProtoMessage()    {}
func (*NodeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{0}
}
func (m *NodeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDetail.Unmarshal(m, b)
}
func (m *NodeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDetail.Marshal(b, m, deterministic)
}
func (dst *NodeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDetail.Merge(dst, src)
}
func (m *NodeDetail) XXX_Size() int {
	return xxx_messageInfo_NodeDetail.Size(m)
}
func (m *NodeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDetail proto.InternalMessageInfo

func (m *NodeDetail) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *NodeDetail) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *NodeDetail) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeDetail) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *NodeDetail) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *NodeDetail) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

func (m *NodeDetail) GetMq() []*MQ {
	if m != nil {
		return m.Mq
	}
	return nil
}

func (m *NodeDetail) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type MQ struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MQ) Reset()         { *m = MQ{} }
func (m *MQ) String() string { return proto.CompactTextString(m) }
func (*MQ) ProtoMessage()    {}
func (*MQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{1}
}
func (m *MQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MQ.Unmarshal(m, b)
}
func (m *MQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MQ.Marshal(b, m, deterministic)
}
func (dst *MQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MQ.Merge(dst, src)
}
func (m *MQ) XXX_Size() int {
	return xxx_messageInfo_MQ.Size(m)
}
func (m *MQ) XXX_DiscardUnknown() {
	xxx_messageInfo_MQ.DiscardUnknown(m)
}

var xxx_messageInfo_MQ proto.InternalMessageInfo

func (m *MQ) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *MQ) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type IdPList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdPList) Reset()         { *m = IdPList{} }
func (m *IdPList) String() string { return proto.CompactTextString(m) }
func (*IdPList) ProtoMessage()    {}
func (*IdPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{2}
}
func (m *IdPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdPList.Unmarshal(m, b)
}
func (m *IdPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdPList.Marshal(b, m, deterministic)
}
func (dst *IdPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdPList.Merge(dst, src)
}
func (m *IdPList) XXX_Size() int {
	return xxx_messageInfo_IdPList.Size(m)
}
func (m *IdPList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdPList.DiscardUnknown(m)
}

var xxx_messageInfo_IdPList proto.InternalMessageInfo

func (m *IdPList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type NamespaceList struct {
	Namespaces           []*Namespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NamespaceList) Reset()         { *m = NamespaceList{} }
func (m *NamespaceList) String() string { return proto.CompactTextString(m) }
func (*NamespaceList) ProtoMessage()    {}
func (*NamespaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{3}
}
func (m *NamespaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceList.Unmarshal(m, b)
}
func (m *NamespaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceList.Marshal(b, m, deterministic)
}
func (dst *NamespaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceList.Merge(dst, src)
}
func (m *NamespaceList) XXX_Size() int {
	return xxx_messageInfo_NamespaceList.Size(m)
}
func (m *NamespaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceList.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceList proto.InternalMessageInfo

func (m *NamespaceList) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

type Namespace struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{4}
}
func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (dst *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(dst, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Namespace) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Namespace) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ServiceDetailList struct {
	Services             []*ServiceDetail `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServiceDetailList) Reset()         { *m = ServiceDetailList{} }
func (m *ServiceDetailList) String() string { return proto.CompactTextString(m) }
func (*ServiceDetailList) ProtoMessage()    {}
func (*ServiceDetailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{5}
}
func (m *ServiceDetailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDetailList.Unmarshal(m, b)
}
func (m *ServiceDetailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDetailList.Marshal(b, m, deterministic)
}
func (dst *ServiceDetailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDetailList.Merge(dst, src)
}
func (m *ServiceDetailList) XXX_Size() int {
	return xxx_messageInfo_ServiceDetailList.Size(m)
}
func (m *ServiceDetailList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDetailList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDetailList proto.InternalMessageInfo

func (m *ServiceDetailList) GetServices() []*ServiceDetail {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServiceDetail struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDetail) Reset()         { *m = ServiceDetail{} }
func (m *ServiceDetail) String() string { return proto.CompactTextString(m) }
func (*ServiceDetail) ProtoMessage()    {}
func (*ServiceDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{6}
}
func (m *ServiceDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDetail.Unmarshal(m, b)
}
func (m *ServiceDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDetail.Marshal(b, m, deterministic)
}
func (dst *ServiceDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDetail.Merge(dst, src)
}
func (m *ServiceDetail) XXX_Size() int {
	return xxx_messageInfo_ServiceDetail.Size(m)
}
func (m *ServiceDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDetail proto.InternalMessageInfo

func (m *ServiceDetail) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ServiceDetail) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceDetail) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ApproveService struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveService) Reset()         { *m = ApproveService{} }
func (m *ApproveService) String() string { return proto.CompactTextString(m) }
func (*ApproveService) ProtoMessage()    {}
func (*ApproveService) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{7}
}
func (m *ApproveService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveService.Unmarshal(m, b)
}
func (m *ApproveService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveService.Marshal(b, m, deterministic)
}
func (dst *ApproveService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveService.Merge(dst, src)
}
func (m *ApproveService) XXX_Size() int {
	return xxx_messageInfo_ApproveService.Size(m)
}
func (m *ApproveService) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveService.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveService proto.InternalMessageInfo

func (m *ApproveService) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type TimeOutBlockRegisterMsqDestination struct {
	TimeOutBlock         int64    `protobuf:"varint,1,opt,name=time_out_block,json=timeOutBlock,proto3" json:"time_out_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeOutBlockRegisterMsqDestination) Reset()         { *m = TimeOutBlockRegisterMsqDestination{} }
func (m *TimeOutBlockRegisterMsqDestination) String() string { return proto.CompactTextString(m) }
func (*TimeOutBlockRegisterMsqDestination) ProtoMessage()    {}
func (*TimeOutBlockRegisterMsqDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{8}
}
func (m *TimeOutBlockRegisterMsqDestination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeOutBlockRegisterMsqDestination.Unmarshal(m, b)
}
func (m *TimeOutBlockRegisterMsqDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeOutBlockRegisterMsqDestination.Marshal(b, m, deterministic)
}
func (dst *TimeOutBlockRegisterMsqDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeOutBlockRegisterMsqDestination.Merge(dst, src)
}
func (m *TimeOutBlockRegisterMsqDestination) XXX_Size() int {
	return xxx_messageInfo_TimeOutBlockRegisterMsqDestination.Size(m)
}
func (m *TimeOutBlockRegisterMsqDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeOutBlockRegisterMsqDestination.DiscardUnknown(m)
}

var xxx_messageInfo_TimeOutBlockRegisterMsqDestination proto.InternalMessageInfo

func (m *TimeOutBlockRegisterMsqDestination) GetTimeOutBlock() int64 {
	if m != nil {
		return m.TimeOutBlock
	}
	return 0
}

type Proxy struct {
	ProxyNodeId          string   `protobuf:"bytes,1,opt,name=proxy_node_id,json=proxyNodeId,proto3" json:"proxy_node_id,omitempty"`
	Config               string   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proxy) Reset()         { *m = Proxy{} }
func (m *Proxy) String() string { return proto.CompactTextString(m) }
func (*Proxy) ProtoMessage()    {}
func (*Proxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{9}
}
func (m *Proxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proxy.Unmarshal(m, b)
}
func (m *Proxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proxy.Marshal(b, m, deterministic)
}
func (dst *Proxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proxy.Merge(dst, src)
}
func (m *Proxy) XXX_Size() int {
	return xxx_messageInfo_Proxy.Size(m)
}
func (m *Proxy) XXX_DiscardUnknown() {
	xxx_messageInfo_Proxy.DiscardUnknown(m)
}

var xxx_messageInfo_Proxy proto.InternalMessageInfo

func (m *Proxy) GetProxyNodeId() string {
	if m != nil {
		return m.ProxyNodeId
	}
	return ""
}

func (m *Proxy) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type BehindNodeList struct {
	Nodes                []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BehindNodeList) Reset()         { *m = BehindNodeList{} }
func (m *BehindNodeList) String() string { return proto.CompactTextString(m) }
func (*BehindNodeList) ProtoMessage()    {}
func (*BehindNodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{10}
}
func (m *BehindNodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BehindNodeList.Unmarshal(m, b)
}
func (m *BehindNodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BehindNodeList.Marshal(b, m, deterministic)
}
func (dst *BehindNodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BehindNodeList.Merge(dst, src)
}
func (m *BehindNodeList) XXX_Size() int {
	return xxx_messageInfo_BehindNodeList.Size(m)
}
func (m *BehindNodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_BehindNodeList.DiscardUnknown(m)
}

var xxx_messageInfo_BehindNodeList proto.InternalMessageInfo

func (m *BehindNodeList) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Request struct {
	RequestId            string         `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MinIdp               int64          `protobuf:"varint,2,opt,name=min_idp,json=minIdp,proto3" json:"min_idp,omitempty"`
	MinAal               float64        `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	MinIal               float64        `protobuf:"fixed64,4,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	RequestTimeout       int64          `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	DataRequestList      []*DataRequest `protobuf:"bytes,6,rep,name=data_request_list,json=dataRequestList,proto3" json:"data_request_list,omitempty"`
	RequestMessageHash   string         `protobuf:"bytes,7,opt,name=request_message_hash,json=requestMessageHash,proto3" json:"request_message_hash,omitempty"`
	ResponseList         []*Response    `protobuf:"bytes,8,rep,name=response_list,json=responseList,proto3" json:"response_list,omitempty"`
	Closed               bool           `protobuf:"varint,9,opt,name=closed,proto3" json:"closed,omitempty"`
	TimedOut             bool           `protobuf:"varint,10,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	CanAddAccessor       bool           `protobuf:"varint,11,opt,name=can_add_accessor,json=canAddAccessor,proto3" json:"can_add_accessor,omitempty"`
	Owner                string         `protobuf:"bytes,12,opt,name=owner,proto3" json:"owner,omitempty"`
	Mode                 int64          `protobuf:"varint,13,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{11}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Request) GetMinIdp() int64 {
	if m != nil {
		return m.MinIdp
	}
	return 0
}

func (m *Request) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *Request) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *Request) GetRequestTimeout() int64 {
	if m != nil {
		return m.RequestTimeout
	}
	return 0
}

func (m *Request) GetDataRequestList() []*DataRequest {
	if m != nil {
		return m.DataRequestList
	}
	return nil
}

func (m *Request) GetRequestMessageHash() string {
	if m != nil {
		return m.RequestMessageHash
	}
	return ""
}

func (m *Request) GetResponseList() []*Response {
	if m != nil {
		return m.ResponseList
	}
	return nil
}

func (m *Request) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func (m *Request) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *Request) GetCanAddAccessor() bool {
	if m != nil {
		return m.CanAddAccessor
	}
	return false
}

func (m *Request) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Request) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type DataRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsIdList             []string `protobuf:"bytes,2,rep,name=as_id_list,json=asIdList,proto3" json:"as_id_list,omitempty"`
	MinAs                int64    `protobuf:"varint,3,opt,name=min_as,json=minAs,proto3" json:"min_as,omitempty"`
	RequestParamsHash    string   `protobuf:"bytes,4,opt,name=request_params_hash,json=requestParamsHash,proto3" json:"request_params_hash,omitempty"`
	AnsweredAsIdList     []string `protobuf:"bytes,5,rep,name=answered_as_id_list,json=answeredAsIdList,proto3" json:"answered_as_id_list,omitempty"`
	ReceivedDataFromList []string `protobuf:"bytes,6,rep,name=received_data_from_list,json=receivedDataFromList,proto3" json:"received_data_from_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{12}
}
func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (dst *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(dst, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *DataRequest) GetAsIdList() []string {
	if m != nil {
		return m.AsIdList
	}
	return nil
}

func (m *DataRequest) GetMinAs() int64 {
	if m != nil {
		return m.MinAs
	}
	return 0
}

func (m *DataRequest) GetRequestParamsHash() string {
	if m != nil {
		return m.RequestParamsHash
	}
	return ""
}

func (m *DataRequest) GetAnsweredAsIdList() []string {
	if m != nil {
		return m.AnsweredAsIdList
	}
	return nil
}

func (m *DataRequest) GetReceivedDataFromList() []string {
	if m != nil {
		return m.ReceivedDataFromList
	}
	return nil
}

type Response struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	Aal                  float64  `protobuf:"fixed64,2,opt,name=aal,proto3" json:"aal,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	IdentityProof        string   `protobuf:"bytes,5,opt,name=identity_proof,json=identityProof,proto3" json:"identity_proof,omitempty"`
	PrivateProofHash     string   `protobuf:"bytes,6,opt,name=private_proof_hash,json=privateProofHash,proto3" json:"private_proof_hash,omitempty"`
	IdpId                string   `protobuf:"bytes,7,opt,name=idp_id,json=idpId,proto3" json:"idp_id,omitempty"`
	ValidProof           string   `protobuf:"bytes,8,opt,name=valid_proof,json=validProof,proto3" json:"valid_proof,omitempty"`
	ValidIal             string   `protobuf:"bytes,9,opt,name=valid_ial,json=validIal,proto3" json:"valid_ial,omitempty"`
	ValidSignature       string   `protobuf:"bytes,10,opt,name=valid_signature,json=validSignature,proto3" json:"valid_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{13}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *Response) GetAal() float64 {
	if m != nil {
		return m.Aal
	}
	return 0
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Response) GetIdentityProof() string {
	if m != nil {
		return m.IdentityProof
	}
	return ""
}

func (m *Response) GetPrivateProofHash() string {
	if m != nil {
		return m.PrivateProofHash
	}
	return ""
}

func (m *Response) GetIdpId() string {
	if m != nil {
		return m.IdpId
	}
	return ""
}

func (m *Response) GetValidProof() string {
	if m != nil {
		return m.ValidProof
	}
	return ""
}

func (m *Response) GetValidIal() string {
	if m != nil {
		return m.ValidIal
	}
	return ""
}

func (m *Response) GetValidSignature() string {
	if m != nil {
		return m.ValidSignature
	}
	return ""
}

type ReportList struct {
	Reports              []*Report `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReportList) Reset()         { *m = ReportList{} }
func (m *ReportList) String() string { return proto.CompactTextString(m) }
func (*ReportList) ProtoMessage()    {}
func (*ReportList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{14}
}
func (m *ReportList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportList.Unmarshal(m, b)
}
func (m *ReportList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportList.Marshal(b, m, deterministic)
}
func (dst *ReportList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportList.Merge(dst, src)
}
func (m *ReportList) XXX_Size() int {
	return xxx_messageInfo_ReportList.Size(m)
}
func (m *ReportList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportList.DiscardUnknown(m)
}

var xxx_messageInfo_ReportList proto.InternalMessageInfo

func (m *ReportList) GetReports() []*Report {
	if m != nil {
		return m.Reports
	}
	return nil
}

type Report struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{15}
}
func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (dst *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(dst, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Report) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Report) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Accessor struct {
	AccessorType         string   `protobuf:"bytes,1,opt,name=accessor_type,json=accessorType,proto3" json:"accessor_type,omitempty"`
	AccessorPublicKey    string   `protobuf:"bytes,2,opt,name=accessor_public_key,json=accessorPublicKey,proto3" json:"accessor_public_key,omitempty"`
	AccessorGroupId      string   `protobuf:"bytes,3,opt,name=accessor_group_id,json=accessorGroupId,proto3" json:"accessor_group_id,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accessor) Reset()         { *m = Accessor{} }
func (m *Accessor) String() string { return proto.CompactTextString(m) }
func (*Accessor) ProtoMessage()    {}
func (*Accessor) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{16}
}
func (m *Accessor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accessor.Unmarshal(m, b)
}
func (m *Accessor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accessor.Marshal(b, m, deterministic)
}
func (dst *Accessor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accessor.Merge(dst, src)
}
func (m *Accessor) XXX_Size() int {
	return xxx_messageInfo_Accessor.Size(m)
}
func (m *Accessor) XXX_DiscardUnknown() {
	xxx_messageInfo_Accessor.DiscardUnknown(m)
}

var xxx_messageInfo_Accessor proto.InternalMessageInfo

func (m *Accessor) GetAccessorType() string {
	if m != nil {
		return m.AccessorType
	}
	return ""
}

func (m *Accessor) GetAccessorPublicKey() string {
	if m != nil {
		return m.AccessorPublicKey
	}
	return ""
}

func (m *Accessor) GetAccessorGroupId() string {
	if m != nil {
		return m.AccessorGroupId
	}
	return ""
}

func (m *Accessor) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Accessor) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type MsqDesList struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsqDesList) Reset()         { *m = MsqDesList{} }
func (m *MsqDesList) String() string { return proto.CompactTextString(m) }
func (*MsqDesList) ProtoMessage()    {}
func (*MsqDesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{17}
}
func (m *MsqDesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsqDesList.Unmarshal(m, b)
}
func (m *MsqDesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsqDesList.Marshal(b, m, deterministic)
}
func (dst *MsqDesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsqDesList.Merge(dst, src)
}
func (m *MsqDesList) XXX_Size() int {
	return xxx_messageInfo_MsqDesList.Size(m)
}
func (m *MsqDesList) XXX_DiscardUnknown() {
	xxx_messageInfo_MsqDesList.DiscardUnknown(m)
}

var xxx_messageInfo_MsqDesList proto.InternalMessageInfo

func (m *MsqDesList) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	First                bool     `protobuf:"varint,4,opt,name=first,proto3" json:"first,omitempty"`
	TimeoutBlock         int64    `protobuf:"varint,5,opt,name=timeout_block,json=timeoutBlock,proto3" json:"timeout_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{18}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *Node) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Node) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Node) GetFirst() bool {
	if m != nil {
		return m.First
	}
	return false
}

func (m *Node) GetTimeoutBlock() int64 {
	if m != nil {
		return m.TimeoutBlock
	}
	return 0
}

type ServiceList struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{19}
}
func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (dst *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(dst, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MinIal               float64  `protobuf:"fixed64,2,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	MinAal               float64  `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Suspended            bool     `protobuf:"varint,5,opt,name=suspended,proto3" json:"suspended,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{20}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Service) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *Service) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *Service) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Service) GetSuspended() bool {
	if m != nil {
		return m.Suspended
	}
	return false
}

type ServiceDesList struct {
	Node                 []*ASNode `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServiceDesList) Reset()         { *m = ServiceDesList{} }
func (m *ServiceDesList) String() string { return proto.CompactTextString(m) }
func (*ServiceDesList) ProtoMessage()    {}
func (*ServiceDesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{21}
}
func (m *ServiceDesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDesList.Unmarshal(m, b)
}
func (m *ServiceDesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDesList.Marshal(b, m, deterministic)
}
func (dst *ServiceDesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDesList.Merge(dst, src)
}
func (m *ServiceDesList) XXX_Size() int {
	return xxx_messageInfo_ServiceDesList.Size(m)
}
func (m *ServiceDesList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDesList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDesList proto.InternalMessageInfo

func (m *ServiceDesList) GetNode() []*ASNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type ASNode struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MinIal               float64  `protobuf:"fixed64,2,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	MinAal               float64  `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	ServiceId            string   `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ASNode) Reset()         { *m = ASNode{} }
func (m *ASNode) String() string { return proto.CompactTextString(m) }
func (*ASNode) ProtoMessage()    {}
func (*ASNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{22}
}
func (m *ASNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASNode.Unmarshal(m, b)
}
func (m *ASNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASNode.Marshal(b, m, deterministic)
}
func (dst *ASNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASNode.Merge(dst, src)
}
func (m *ASNode) XXX_Size() int {
	return xxx_messageInfo_ASNode.Size(m)
}
func (m *ASNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ASNode.DiscardUnknown(m)
}

var xxx_messageInfo_ASNode proto.InternalMessageInfo

func (m *ASNode) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ASNode) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *ASNode) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *ASNode) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ASNode) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type RPList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPList) Reset()         { *m = RPList{} }
func (m *RPList) String() string { return proto.CompactTextString(m) }
func (*RPList) ProtoMessage()    {}
func (*RPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{23}
}
func (m *RPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPList.Unmarshal(m, b)
}
func (m *RPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPList.Marshal(b, m, deterministic)
}
func (dst *RPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPList.Merge(dst, src)
}
func (m *RPList) XXX_Size() int {
	return xxx_messageInfo_RPList.Size(m)
}
func (m *RPList) XXX_DiscardUnknown() {
	xxx_messageInfo_RPList.DiscardUnknown(m)
}

var xxx_messageInfo_RPList proto.InternalMessageInfo

func (m *RPList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type ASList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ASList) Reset()         { *m = ASList{} }
func (m *ASList) String() string { return proto.CompactTextString(m) }
func (*ASList) ProtoMessage()    {}
func (*ASList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{24}
}
func (m *ASList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASList.Unmarshal(m, b)
}
func (m *ASList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASList.Marshal(b, m, deterministic)
}
func (dst *ASList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASList.Merge(dst, src)
}
func (m *ASList) XXX_Size() int {
	return xxx_messageInfo_ASList.Size(m)
}
func (m *ASList) XXX_DiscardUnknown() {
	xxx_messageInfo_ASList.DiscardUnknown(m)
}

var xxx_messageInfo_ASList proto.InternalMessageInfo

func (m *ASList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type AllList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllList) Reset()         { *m = AllList{} }
func (m *AllList) String() string { return proto.CompactTextString(m) }
func (*AllList) ProtoMessage()    {}
func (*AllList) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_01d1e109b93d321d, []int{25}
}
func (m *AllList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllList.Unmarshal(m, b)
}
func (m *AllList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllList.Marshal(b, m, deterministic)
}
func (dst *AllList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllList.Merge(dst, src)
}
func (m *AllList) XXX_Size() int {
	return xxx_messageInfo_AllList.Size(m)
}
func (m *AllList) XXX_DiscardUnknown() {
	xxx_messageInfo_AllList.DiscardUnknown(m)
}

var xxx_messageInfo_AllList proto.InternalMessageInfo

func (m *AllList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeDetail)(nil), "NodeDetail")
	proto.RegisterType((*MQ)(nil), "MQ")
	proto.RegisterType((*IdPList)(nil), "IdPList")
	proto.RegisterType((*NamespaceList)(nil), "NamespaceList")
	proto.RegisterType((*Namespace)(nil), "Namespace")
	proto.RegisterType((*ServiceDetailList)(nil), "ServiceDetailList")
	proto.RegisterType((*ServiceDetail)(nil), "ServiceDetail")
	proto.RegisterType((*ApproveService)(nil), "ApproveService")
	proto.RegisterType((*TimeOutBlockRegisterMsqDestination)(nil), "TimeOutBlockRegisterMsqDestination")
	proto.RegisterType((*Proxy)(nil), "Proxy")
	proto.RegisterType((*BehindNodeList)(nil), "BehindNodeList")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ReportList)(nil), "ReportList")
	proto.RegisterType((*Report)(nil), "Report")
	proto.RegisterType((*Accessor)(nil), "Accessor")
	proto.RegisterType((*MsqDesList)(nil), "MsqDesList")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*ServiceList)(nil), "ServiceList")
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*ServiceDesList)(nil), "ServiceDesList")
	proto.RegisterType((*ASNode)(nil), "ASNode")
	proto.RegisterType((*RPList)(nil), "RPList")
	proto.RegisterType((*ASList)(nil), "ASList")
	proto.RegisterType((*AllList)(nil), "AllList")
}

func init() { proto.RegisterFile("protos/data/data.proto", fileDescriptor_data_01d1e109b93d321d) }

var fileDescriptor_data_01d1e109b93d321d = []byte{
	// 1257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0x1c, 0x45,
	0x10, 0xd6, 0xec, 0x7a, 0xff, 0x6a, 0xbd, 0x6b, 0x7b, 0xf2, 0x37, 0x52, 0x82, 0xb0, 0x87, 0x00,
	0x4b, 0x44, 0x36, 0x28, 0x11, 0x12, 0x12, 0x07, 0xb4, 0x21, 0x02, 0x36, 0xe0, 0xc4, 0x99, 0xe4,
	0x3e, 0xea, 0x4c, 0xb7, 0xed, 0x56, 0x66, 0xa6, 0xc7, 0xd3, 0xbd, 0x4e, 0x7c, 0xe7, 0xc4, 0x89,
	0xb7, 0x41, 0x1c, 0x79, 0x1a, 0x1e, 0x81, 0x2b, 0xaa, 0xea, 0xee, 0xd9, 0x59, 0xf2, 0x63, 0x71,
	0xb1, 0xba, 0xbe, 0xaf, 0xd6, 0x5d, 0xf5, 0x55, 0x75, 0xd5, 0xc0, 0xf5, 0xaa, 0x56, 0x46, 0xe9,
	0x7b, 0x9c, 0x19, 0x46, 0x7f, 0xe6, 0x04, 0xc4, 0x7f, 0x07, 0x00, 0x4f, 0x14, 0x17, 0x8f, 0x84,
	0x61, 0x32, 0x0f, 0x3f, 0x02, 0xa8, 0x56, 0x2f, 0x73, 0x99, 0xa5, 0xaf, 0xc4, 0x45, 0x14, 0xec,
	0x07, 0xb3, 0x51, 0x32, 0xb2, 0xc8, 0xcf, 0xe2, 0x22, 0xbc, 0x03, 0x7b, 0x05, 0xd3, 0x46, 0xd4,
	0x69, 0xcb, 0xab, 0x43, 0x5e, 0x3b, 0x96, 0x38, 0x6a, 0x7c, 0x6f, 0xc2, 0xa8, 0x54, 0x5c, 0xa4,
	0x25, 0x2b, 0x44, 0xd4, 0x25, 0x9f, 0x21, 0x02, 0x4f, 0x58, 0x21, 0xc2, 0x10, 0xb6, 0x6a, 0x95,
	0x8b, 0x68, 0x8b, 0x70, 0x3a, 0x87, 0x37, 0x60, 0x50, 0xb0, 0x37, 0xa9, 0x64, 0x79, 0xd4, 0xdb,
	0x0f, 0x66, 0x41, 0xd2, 0x2f, 0xd8, 0x9b, 0x25, 0xcb, 0x3d, 0xc1, 0x58, 0x1e, 0xf5, 0x1b, 0x62,
	0xc1, 0xf2, 0xf0, 0x0a, 0x74, 0x8a, 0xb3, 0x68, 0xb0, 0xdf, 0x9d, 0x8d, 0xef, 0x77, 0xe7, 0x87,
	0xcf, 0x92, 0x4e, 0x71, 0x16, 0x5e, 0x87, 0x3e, 0xcb, 0x8c, 0x3c, 0x17, 0xd1, 0x70, 0x3f, 0x98,
	0x0d, 0x13, 0x67, 0xc5, 0x33, 0xe8, 0x1c, 0x3e, 0x0b, 0xa7, 0xd0, 0x91, 0x95, 0x4b, 0xac, 0x23,
	0x2b, 0x0c, 0xa4, 0x52, 0xb5, 0xa1, 0x24, 0xba, 0x09, 0x9d, 0xe3, 0x18, 0x06, 0x4b, 0x7e, 0xf4,
	0x8b, 0xd4, 0x06, 0xaf, 0xa6, 0x24, 0x24, 0x8f, 0x82, 0xfd, 0xee, 0x6c, 0x94, 0xf4, 0xd1, 0x5c,
	0xf2, 0xf8, 0x5b, 0x98, 0x60, 0x22, 0xba, 0x62, 0x99, 0x20, 0xcf, 0x3b, 0x00, 0xa5, 0x07, 0x34,
	0x39, 0x8f, 0xef, 0xc3, 0xbc, 0xf1, 0x49, 0x5a, 0x6c, 0x9c, 0xc1, 0xa8, 0x21, 0xc2, 0x5b, 0x30,
	0x6a, 0x28, 0xaf, 0x78, 0x03, 0x84, 0xfb, 0x30, 0xe6, 0x42, 0x67, 0xb5, 0xac, 0x8c, 0x54, 0xa5,
	0xd3, 0xba, 0x0d, 0xb5, 0xf2, 0xed, 0x6e, 0xe4, 0xfb, 0x1d, 0xec, 0x3d, 0x17, 0xf5, 0xb9, 0xcc,
	0x5c, 0x6d, 0x5d, 0x94, 0x43, 0x6d, 0x41, 0x1f, 0xe3, 0x74, 0xbe, 0xe1, 0x95, 0x34, 0x7c, 0x2c,
	0x61, 0xb2, 0x41, 0x61, 0x73, 0x38, 0xd2, 0xea, 0x41, 0xa1, 0x3a, 0x64, 0xc9, 0xc3, 0x03, 0xd8,
	0xf6, 0x34, 0xd5, 0xdc, 0xc5, 0xea, 0x30, 0x2a, 0xfb, 0xfb, 0x62, 0x9d, 0xc1, 0x74, 0x51, 0x55,
	0xb5, 0x3a, 0x17, 0xee, 0xc6, 0x96, 0x67, 0xb0, 0xe1, 0xf9, 0x18, 0xe2, 0x17, 0xb2, 0x10, 0x4f,
	0x57, 0xe6, 0x61, 0xae, 0xb2, 0x57, 0x89, 0x38, 0x91, 0xd8, 0x76, 0x87, 0xfa, 0xec, 0x91, 0xd0,
	0x46, 0x96, 0x8c, 0x34, 0xb9, 0x0d, 0x53, 0x23, 0x0b, 0x91, 0xaa, 0x95, 0x49, 0x5f, 0xa2, 0x1f,
	0xfd, 0x97, 0x6e, 0xb2, 0x6d, 0x5a, 0xbf, 0x8d, 0xbf, 0x87, 0xde, 0x51, 0xad, 0xde, 0x5c, 0x84,
	0x31, 0x4c, 0x2a, 0x3c, 0xa4, 0xeb, 0x5a, 0x53, 0xe8, 0x04, 0x3e, 0xa1, 0x82, 0x63, 0x40, 0x99,
	0x2a, 0x8f, 0xe5, 0x89, 0xcb, 0xcb, 0x59, 0xf1, 0x67, 0x30, 0x7d, 0x28, 0x4e, 0x65, 0xc9, 0xd1,
	0x8f, 0x34, 0xbe, 0x0a, 0x3d, 0xfc, 0x3f, 0xda, 0x75, 0x8c, 0x35, 0xe2, 0xbf, 0xba, 0x30, 0x48,
	0xc4, 0xd9, 0x4a, 0x68, 0x83, 0x42, 0xd6, 0xf6, 0xd8, 0x12, 0xd2, 0x21, 0x4b, 0x4e, 0xfd, 0x2e,
	0xcb, 0x54, 0xf2, 0xca, 0xb5, 0x65, 0xbf, 0x90, 0xe5, 0x92, 0x57, 0x9e, 0xc0, 0x87, 0xd0, 0x75,
	0x0f, 0x41, 0x96, 0x0b, 0xf7, 0x42, 0xf0, 0x17, 0x2c, 0xa7, 0x17, 0x65, 0x09, 0x7c, 0x3a, 0x9f,
	0xc3, 0x8e, 0xbf, 0x09, 0x53, 0x57, 0x2b, 0x43, 0x6f, 0xab, 0x9b, 0x4c, 0x1d, 0xfc, 0xc2, 0xa2,
	0xe1, 0x37, 0xb0, 0x87, 0x53, 0x21, 0xf5, 0xde, 0xb9, 0xd4, 0x26, 0xea, 0x53, 0x87, 0x6c, 0xcf,
	0x1f, 0x31, 0xc3, 0x5c, 0xec, 0xc9, 0x0e, 0x5f, 0x1b, 0x94, 0xee, 0x57, 0x70, 0xd5, 0xff, 0xa8,
	0x10, 0x5a, 0xb3, 0x13, 0x91, 0x9e, 0x32, 0x7d, 0x1a, 0x0d, 0x28, 0xad, 0xd0, 0x71, 0x87, 0x96,
	0xfa, 0x89, 0xe9, 0xd3, 0x70, 0x0e, 0x93, 0x5a, 0xe8, 0x4a, 0x95, 0x5a, 0xd8, 0x7b, 0x86, 0x74,
	0xcf, 0x68, 0x9e, 0x38, 0x34, 0xd9, 0xf6, 0x3c, 0xdd, 0x80, 0xd2, 0xe7, 0x4a, 0x0b, 0x1e, 0x8d,
	0x6c, 0x2f, 0x58, 0x0b, 0x27, 0x0c, 0x26, 0xc5, 0xb1, 0xcc, 0x11, 0x10, 0x35, 0x24, 0xe0, 0xe9,
	0xca, 0x84, 0x33, 0xd8, 0xcd, 0x58, 0x99, 0x32, 0xce, 0x53, 0x96, 0x65, 0x42, 0x6b, 0x55, 0x47,
	0x63, 0xf2, 0x99, 0x66, 0xac, 0x5c, 0x70, 0xbe, 0x70, 0x28, 0xd6, 0x4b, 0xbd, 0x2e, 0x45, 0x1d,
	0x6d, 0x53, 0xc4, 0xd6, 0xc0, 0xc1, 0x50, 0x28, 0x2e, 0xa2, 0x89, 0x1d, 0x0c, 0x78, 0x8e, 0xff,
	0x09, 0x60, 0xdc, 0xd2, 0xe2, 0xb2, 0x07, 0x71, 0x0b, 0x80, 0xe9, 0x54, 0x72, 0x9b, 0x64, 0x87,
	0xba, 0x61, 0xc8, 0xf4, 0x92, 0x53, 0x56, 0xd7, 0xa0, 0x4f, 0xc5, 0xd4, 0x54, 0xcb, 0x6e, 0xd2,
	0xc3, 0x5a, 0xea, 0x70, 0x0e, 0x57, 0xbc, 0x9c, 0x15, 0xab, 0x59, 0xa1, 0xad, 0x9a, 0x76, 0x50,
	0xee, 0x39, 0xea, 0x88, 0x18, 0x12, 0xf3, 0x2e, 0x5c, 0x61, 0xa5, 0x7e, 0x2d, 0x6a, 0xc1, 0xd3,
	0xd6, 0x6d, 0x3d, 0xba, 0x6d, 0xd7, 0x53, 0x0b, 0x7f, 0xeb, 0xd7, 0x70, 0xa3, 0x16, 0x99, 0x90,
	0xe7, 0x82, 0xa7, 0x54, 0xf0, 0xe3, 0x5a, 0x15, 0xeb, 0x6a, 0x8f, 0x92, 0xab, 0x9e, 0xc6, 0x44,
	0x7f, 0xa8, 0x55, 0x81, 0x3f, 0x8b, 0xff, 0xe8, 0xc0, 0xd0, 0x57, 0x27, 0xdc, 0x85, 0x2e, 0x76,
	0x5a, 0x40, 0x9d, 0x86, 0x47, 0x44, 0xb0, 0x29, 0x3b, 0x16, 0x61, 0x2c, 0xc7, 0x9a, 0x69, 0xc3,
	0xcc, 0x4a, 0xbb, 0xd1, 0xef, 0x2c, 0x9c, 0x76, 0x5a, 0x9e, 0x94, 0xcc, 0xac, 0x6a, 0x3f, 0xfd,
	0xd7, 0x40, 0xf8, 0x29, 0x4c, 0x25, 0x17, 0xa5, 0x91, 0xe6, 0x22, 0xad, 0x6a, 0xa5, 0x8e, 0xa9,
	0x5b, 0x47, 0xc9, 0xc4, 0xa3, 0x47, 0x08, 0x86, 0x5f, 0x42, 0x58, 0xd5, 0xf2, 0x9c, 0x19, 0x61,
	0xbd, 0xac, 0x44, 0x7d, 0x72, 0xdd, 0x75, 0x0c, 0x79, 0x92, 0x42, 0xd7, 0xa0, 0x2f, 0x79, 0x85,
	0x15, 0xb2, 0x2d, 0xd9, 0x93, 0xbc, 0x5a, 0xf2, 0xf0, 0x63, 0x18, 0x9f, 0xb3, 0x5c, 0x72, 0x77,
	0xd1, 0x90, 0x38, 0x20, 0xc8, 0xde, 0x72, 0x13, 0x46, 0xd6, 0x01, 0x93, 0x1d, 0xd9, 0x05, 0x46,
	0x80, 0x7b, 0x58, 0x96, 0x5c, 0x67, 0x03, 0xe4, 0x32, 0x25, 0xf8, 0xb9, 0x47, 0xe3, 0x7b, 0x00,
	0x89, 0xc0, 0xb5, 0x42, 0xf2, 0x1f, 0xc0, 0xa0, 0x26, 0xcb, 0x8f, 0xdf, 0xc1, 0xdc, 0xb2, 0x89,
	0xc7, 0xe3, 0xc7, 0xd0, 0xb7, 0x10, 0x6a, 0x58, 0x08, 0x73, 0xaa, 0x7c, 0x6b, 0x39, 0x0b, 0x1b,
	0xb6, 0xaa, 0x65, 0x26, 0x9c, 0xde, 0xd6, 0xc0, 0x86, 0xc5, 0x82, 0x3a, 0xbd, 0xe9, 0x1c, 0xff,
	0x19, 0xc0, 0xb0, 0xe9, 0xf3, 0x4f, 0x60, 0xe2, 0x5f, 0x42, 0x6a, 0x2e, 0x2a, 0xbf, 0x6c, 0xb6,
	0x3d, 0xf8, 0xe2, 0xa2, 0x12, 0xd8, 0x7e, 0x8d, 0xd3, 0x5b, 0x3b, 0x7e, 0xcf, 0x53, 0x47, 0xed,
	0x2f, 0x82, 0xc6, 0xff, 0xa4, 0x56, 0x2b, 0xd2, 0xd9, 0x86, 0xb0, 0xe3, 0x89, 0x1f, 0x11, 0xb7,
	0x23, 0xd4, 0xcd, 0xf4, 0xad, 0xf6, 0x4c, 0x5f, 0x3f, 0xc0, 0x5e, 0xeb, 0x01, 0xc6, 0x5f, 0x00,
	0xd8, 0xa9, 0x4e, 0xc2, 0xdd, 0x6c, 0x0f, 0xd5, 0xf1, 0xfd, 0xde, 0x1c, 0xc7, 0xad, 0x9f, 0xad,
	0xbf, 0x06, 0xb0, 0x85, 0xf6, 0x3b, 0x3a, 0xb3, 0xb5, 0xc0, 0xdd, 0xdc, 0x2e, 0x9b, 0x79, 0xfe,
	0xae, 0x55, 0x84, 0xc1, 0x1c, 0xcb, 0x5a, 0x1b, 0x17, 0xa3, 0x35, 0x50, 0x3b, 0x37, 0x3f, 0xdd,
	0x3e, 0xe9, 0xad, 0xf7, 0x89, 0xf2, 0xfb, 0xe4, 0x01, 0x8c, 0xdd, 0xfa, 0xa2, 0x90, 0x6f, 0xbf,
	0xb5, 0x6b, 0x87, 0x7e, 0xd7, 0xb6, 0xb6, 0xec, 0xef, 0x01, 0x0c, 0xfc, 0xd2, 0xbb, 0x64, 0x9e,
	0xb4, 0xa6, 0x7c, 0x67, 0x63, 0xca, 0xbf, 0x77, 0x2f, 0xbc, 0x4f, 0x71, 0x7c, 0x85, 0x2b, 0x5d,
	0x89, 0x92, 0x0b, 0x4e, 0xa9, 0x0c, 0x93, 0x35, 0x10, 0xdf, 0x85, 0x69, 0xb3, 0xf8, 0xbd, 0xfa,
	0x5b, 0x28, 0x5b, 0xd3, 0xb3, 0x8b, 0xe7, 0x24, 0x3f, 0x81, 0xf1, 0x6f, 0x01, 0xf4, 0x2d, 0xb0,
	0xf9, 0xb9, 0xd4, 0x56, 0xfb, 0xff, 0x87, 0xbe, 0xa9, 0xc5, 0xd6, 0x7f, 0xb5, 0x58, 0x67, 0xd6,
	0xdb, 0xf8, 0x3e, 0x38, 0x80, 0x7e, 0x72, 0xc9, 0xa7, 0xdb, 0x01, 0x86, 0xfb, 0x61, 0x97, 0x18,
	0x06, 0x8b, 0x3c, 0xff, 0xa0, 0xcf, 0xcb, 0x3e, 0x7d, 0x40, 0x3f, 0xf8, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xd7, 0x92, 0x46, 0x90, 0x5a, 0x0b, 0x00, 0x00,
}
