// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/data/data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyVersions struct {
	Versions             []int64  `protobuf:"varint,1,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyVersions) Reset()         { *m = KeyVersions{} }
func (m *KeyVersions) String() string { return proto.CompactTextString(m) }
func (*KeyVersions) ProtoMessage()    {}
func (*KeyVersions) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{0}
}

func (m *KeyVersions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyVersions.Unmarshal(m, b)
}
func (m *KeyVersions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyVersions.Marshal(b, m, deterministic)
}
func (m *KeyVersions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyVersions.Merge(m, src)
}
func (m *KeyVersions) XXX_Size() int {
	return xxx_messageInfo_KeyVersions.Size(m)
}
func (m *KeyVersions) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyVersions.DiscardUnknown(m)
}

var xxx_messageInfo_KeyVersions proto.InternalMessageInfo

func (m *KeyVersions) GetVersions() []int64 {
	if m != nil {
		return m.Versions
	}
	return nil
}

type NodeDetail struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey      string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName             string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal               float64  `protobuf:"fixed64,5,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal               float64  `protobuf:"fixed64,6,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	Mq                   []*MQ    `protobuf:"bytes,7,rep,name=mq,proto3" json:"mq,omitempty"`
	Active               bool     `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	ProxyNodeId          string   `protobuf:"bytes,9,opt,name=proxy_node_id,json=proxyNodeId,proto3" json:"proxy_node_id,omitempty"`
	ProxyConfig          string   `protobuf:"bytes,10,opt,name=proxy_config,json=proxyConfig,proto3" json:"proxy_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDetail) Reset()         { *m = NodeDetail{} }
func (m *NodeDetail) String() string { return proto.CompactTextString(m) }
func (*NodeDetail) ProtoMessage()    {}
func (*NodeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{1}
}

func (m *NodeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDetail.Unmarshal(m, b)
}
func (m *NodeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDetail.Marshal(b, m, deterministic)
}
func (m *NodeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDetail.Merge(m, src)
}
func (m *NodeDetail) XXX_Size() int {
	return xxx_messageInfo_NodeDetail.Size(m)
}
func (m *NodeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDetail proto.InternalMessageInfo

func (m *NodeDetail) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *NodeDetail) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *NodeDetail) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeDetail) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *NodeDetail) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *NodeDetail) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

func (m *NodeDetail) GetMq() []*MQ {
	if m != nil {
		return m.Mq
	}
	return nil
}

func (m *NodeDetail) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *NodeDetail) GetProxyNodeId() string {
	if m != nil {
		return m.ProxyNodeId
	}
	return ""
}

func (m *NodeDetail) GetProxyConfig() string {
	if m != nil {
		return m.ProxyConfig
	}
	return ""
}

type MQ struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MQ) Reset()         { *m = MQ{} }
func (m *MQ) String() string { return proto.CompactTextString(m) }
func (*MQ) ProtoMessage()    {}
func (*MQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{2}
}

func (m *MQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MQ.Unmarshal(m, b)
}
func (m *MQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MQ.Marshal(b, m, deterministic)
}
func (m *MQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MQ.Merge(m, src)
}
func (m *MQ) XXX_Size() int {
	return xxx_messageInfo_MQ.Size(m)
}
func (m *MQ) XXX_DiscardUnknown() {
	xxx_messageInfo_MQ.DiscardUnknown(m)
}

var xxx_messageInfo_MQ proto.InternalMessageInfo

func (m *MQ) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *MQ) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type IdPList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdPList) Reset()         { *m = IdPList{} }
func (m *IdPList) String() string { return proto.CompactTextString(m) }
func (*IdPList) ProtoMessage()    {}
func (*IdPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{3}
}

func (m *IdPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdPList.Unmarshal(m, b)
}
func (m *IdPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdPList.Marshal(b, m, deterministic)
}
func (m *IdPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdPList.Merge(m, src)
}
func (m *IdPList) XXX_Size() int {
	return xxx_messageInfo_IdPList.Size(m)
}
func (m *IdPList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdPList.DiscardUnknown(m)
}

var xxx_messageInfo_IdPList proto.InternalMessageInfo

func (m *IdPList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type NamespaceList struct {
	Namespaces           []*Namespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NamespaceList) Reset()         { *m = NamespaceList{} }
func (m *NamespaceList) String() string { return proto.CompactTextString(m) }
func (*NamespaceList) ProtoMessage()    {}
func (*NamespaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{4}
}

func (m *NamespaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceList.Unmarshal(m, b)
}
func (m *NamespaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceList.Marshal(b, m, deterministic)
}
func (m *NamespaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceList.Merge(m, src)
}
func (m *NamespaceList) XXX_Size() int {
	return xxx_messageInfo_NamespaceList.Size(m)
}
func (m *NamespaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceList.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceList proto.InternalMessageInfo

func (m *NamespaceList) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

type Namespace struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{5}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Namespace) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Namespace) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ServiceDetailList struct {
	Services             []*ServiceDetail `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServiceDetailList) Reset()         { *m = ServiceDetailList{} }
func (m *ServiceDetailList) String() string { return proto.CompactTextString(m) }
func (*ServiceDetailList) ProtoMessage()    {}
func (*ServiceDetailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{6}
}

func (m *ServiceDetailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDetailList.Unmarshal(m, b)
}
func (m *ServiceDetailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDetailList.Marshal(b, m, deterministic)
}
func (m *ServiceDetailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDetailList.Merge(m, src)
}
func (m *ServiceDetailList) XXX_Size() int {
	return xxx_messageInfo_ServiceDetailList.Size(m)
}
func (m *ServiceDetailList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDetailList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDetailList proto.InternalMessageInfo

func (m *ServiceDetailList) GetServices() []*ServiceDetail {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServiceDetail struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	DataSchema           string   `protobuf:"bytes,3,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`
	DataSchemaVersion    string   `protobuf:"bytes,4,opt,name=data_schema_version,json=dataSchemaVersion,proto3" json:"data_schema_version,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDetail) Reset()         { *m = ServiceDetail{} }
func (m *ServiceDetail) String() string { return proto.CompactTextString(m) }
func (*ServiceDetail) ProtoMessage()    {}
func (*ServiceDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{7}
}

func (m *ServiceDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDetail.Unmarshal(m, b)
}
func (m *ServiceDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDetail.Marshal(b, m, deterministic)
}
func (m *ServiceDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDetail.Merge(m, src)
}
func (m *ServiceDetail) XXX_Size() int {
	return xxx_messageInfo_ServiceDetail.Size(m)
}
func (m *ServiceDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDetail proto.InternalMessageInfo

func (m *ServiceDetail) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ServiceDetail) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceDetail) GetDataSchema() string {
	if m != nil {
		return m.DataSchema
	}
	return ""
}

func (m *ServiceDetail) GetDataSchemaVersion() string {
	if m != nil {
		return m.DataSchemaVersion
	}
	return ""
}

func (m *ServiceDetail) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ApproveService struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveService) Reset()         { *m = ApproveService{} }
func (m *ApproveService) String() string { return proto.CompactTextString(m) }
func (*ApproveService) ProtoMessage()    {}
func (*ApproveService) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{8}
}

func (m *ApproveService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveService.Unmarshal(m, b)
}
func (m *ApproveService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveService.Marshal(b, m, deterministic)
}
func (m *ApproveService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveService.Merge(m, src)
}
func (m *ApproveService) XXX_Size() int {
	return xxx_messageInfo_ApproveService.Size(m)
}
func (m *ApproveService) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveService.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveService proto.InternalMessageInfo

func (m *ApproveService) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type TimeOutBlockRegisterIdentity struct {
	TimeOutBlock         int64    `protobuf:"varint,1,opt,name=time_out_block,json=timeOutBlock,proto3" json:"time_out_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeOutBlockRegisterIdentity) Reset()         { *m = TimeOutBlockRegisterIdentity{} }
func (m *TimeOutBlockRegisterIdentity) String() string { return proto.CompactTextString(m) }
func (*TimeOutBlockRegisterIdentity) ProtoMessage()    {}
func (*TimeOutBlockRegisterIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{9}
}

func (m *TimeOutBlockRegisterIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeOutBlockRegisterIdentity.Unmarshal(m, b)
}
func (m *TimeOutBlockRegisterIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeOutBlockRegisterIdentity.Marshal(b, m, deterministic)
}
func (m *TimeOutBlockRegisterIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeOutBlockRegisterIdentity.Merge(m, src)
}
func (m *TimeOutBlockRegisterIdentity) XXX_Size() int {
	return xxx_messageInfo_TimeOutBlockRegisterIdentity.Size(m)
}
func (m *TimeOutBlockRegisterIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeOutBlockRegisterIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_TimeOutBlockRegisterIdentity proto.InternalMessageInfo

func (m *TimeOutBlockRegisterIdentity) GetTimeOutBlock() int64 {
	if m != nil {
		return m.TimeOutBlock
	}
	return 0
}

type Proxy struct {
	ProxyNodeId          string   `protobuf:"bytes,1,opt,name=proxy_node_id,json=proxyNodeId,proto3" json:"proxy_node_id,omitempty"`
	Config               string   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proxy) Reset()         { *m = Proxy{} }
func (m *Proxy) String() string { return proto.CompactTextString(m) }
func (*Proxy) ProtoMessage()    {}
func (*Proxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{10}
}

func (m *Proxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proxy.Unmarshal(m, b)
}
func (m *Proxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proxy.Marshal(b, m, deterministic)
}
func (m *Proxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proxy.Merge(m, src)
}
func (m *Proxy) XXX_Size() int {
	return xxx_messageInfo_Proxy.Size(m)
}
func (m *Proxy) XXX_DiscardUnknown() {
	xxx_messageInfo_Proxy.DiscardUnknown(m)
}

var xxx_messageInfo_Proxy proto.InternalMessageInfo

func (m *Proxy) GetProxyNodeId() string {
	if m != nil {
		return m.ProxyNodeId
	}
	return ""
}

func (m *Proxy) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type BehindNodeList struct {
	Nodes                []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BehindNodeList) Reset()         { *m = BehindNodeList{} }
func (m *BehindNodeList) String() string { return proto.CompactTextString(m) }
func (*BehindNodeList) ProtoMessage()    {}
func (*BehindNodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{11}
}

func (m *BehindNodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BehindNodeList.Unmarshal(m, b)
}
func (m *BehindNodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BehindNodeList.Marshal(b, m, deterministic)
}
func (m *BehindNodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BehindNodeList.Merge(m, src)
}
func (m *BehindNodeList) XXX_Size() int {
	return xxx_messageInfo_BehindNodeList.Size(m)
}
func (m *BehindNodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_BehindNodeList.DiscardUnknown(m)
}

var xxx_messageInfo_BehindNodeList proto.InternalMessageInfo

func (m *BehindNodeList) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Request struct {
	RequestId            string         `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MinIdp               int64          `protobuf:"varint,2,opt,name=min_idp,json=minIdp,proto3" json:"min_idp,omitempty"`
	MinAal               float64        `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	MinIal               float64        `protobuf:"fixed64,4,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	RequestTimeout       int64          `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	IdpIdList            []string       `protobuf:"bytes,6,rep,name=idp_id_list,json=idpIdList,proto3" json:"idp_id_list,omitempty"`
	DataRequestList      []*DataRequest `protobuf:"bytes,7,rep,name=data_request_list,json=dataRequestList,proto3" json:"data_request_list,omitempty"`
	RequestMessageHash   string         `protobuf:"bytes,8,opt,name=request_message_hash,json=requestMessageHash,proto3" json:"request_message_hash,omitempty"`
	ResponseList         []*Response    `protobuf:"bytes,9,rep,name=response_list,json=responseList,proto3" json:"response_list,omitempty"`
	Closed               bool           `protobuf:"varint,10,opt,name=closed,proto3" json:"closed,omitempty"`
	TimedOut             bool           `protobuf:"varint,11,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Purpose              string         `protobuf:"bytes,12,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Owner                string         `protobuf:"bytes,13,opt,name=owner,proto3" json:"owner,omitempty"`
	Mode                 int64          `protobuf:"varint,14,opt,name=mode,proto3" json:"mode,omitempty"`
	UseCount             int64          `protobuf:"varint,15,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	CreationBlockHeight  int64          `protobuf:"varint,16,opt,name=creation_block_height,json=creationBlockHeight,proto3" json:"creation_block_height,omitempty"`
	ChainId              string         `protobuf:"bytes,17,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{12}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Request) GetMinIdp() int64 {
	if m != nil {
		return m.MinIdp
	}
	return 0
}

func (m *Request) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *Request) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *Request) GetRequestTimeout() int64 {
	if m != nil {
		return m.RequestTimeout
	}
	return 0
}

func (m *Request) GetIdpIdList() []string {
	if m != nil {
		return m.IdpIdList
	}
	return nil
}

func (m *Request) GetDataRequestList() []*DataRequest {
	if m != nil {
		return m.DataRequestList
	}
	return nil
}

func (m *Request) GetRequestMessageHash() string {
	if m != nil {
		return m.RequestMessageHash
	}
	return ""
}

func (m *Request) GetResponseList() []*Response {
	if m != nil {
		return m.ResponseList
	}
	return nil
}

func (m *Request) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func (m *Request) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *Request) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Request) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Request) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Request) GetUseCount() int64 {
	if m != nil {
		return m.UseCount
	}
	return 0
}

func (m *Request) GetCreationBlockHeight() int64 {
	if m != nil {
		return m.CreationBlockHeight
	}
	return 0
}

func (m *Request) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type DataRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsIdList             []string `protobuf:"bytes,2,rep,name=as_id_list,json=asIdList,proto3" json:"as_id_list,omitempty"`
	MinAs                int64    `protobuf:"varint,3,opt,name=min_as,json=minAs,proto3" json:"min_as,omitempty"`
	RequestParamsHash    string   `protobuf:"bytes,4,opt,name=request_params_hash,json=requestParamsHash,proto3" json:"request_params_hash,omitempty"`
	AnsweredAsIdList     []string `protobuf:"bytes,5,rep,name=answered_as_id_list,json=answeredAsIdList,proto3" json:"answered_as_id_list,omitempty"`
	ReceivedDataFromList []string `protobuf:"bytes,6,rep,name=received_data_from_list,json=receivedDataFromList,proto3" json:"received_data_from_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{13}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *DataRequest) GetAsIdList() []string {
	if m != nil {
		return m.AsIdList
	}
	return nil
}

func (m *DataRequest) GetMinAs() int64 {
	if m != nil {
		return m.MinAs
	}
	return 0
}

func (m *DataRequest) GetRequestParamsHash() string {
	if m != nil {
		return m.RequestParamsHash
	}
	return ""
}

func (m *DataRequest) GetAnsweredAsIdList() []string {
	if m != nil {
		return m.AnsweredAsIdList
	}
	return nil
}

func (m *DataRequest) GetReceivedDataFromList() []string {
	if m != nil {
		return m.ReceivedDataFromList
	}
	return nil
}

type Response struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	Aal                  float64  `protobuf:"fixed64,2,opt,name=aal,proto3" json:"aal,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	IdentityProof        string   `protobuf:"bytes,5,opt,name=identity_proof,json=identityProof,proto3" json:"identity_proof,omitempty"`
	PrivateProofHash     string   `protobuf:"bytes,6,opt,name=private_proof_hash,json=privateProofHash,proto3" json:"private_proof_hash,omitempty"`
	IdpId                string   `protobuf:"bytes,7,opt,name=idp_id,json=idpId,proto3" json:"idp_id,omitempty"`
	ValidProof           string   `protobuf:"bytes,8,opt,name=valid_proof,json=validProof,proto3" json:"valid_proof,omitempty"`
	ValidIal             string   `protobuf:"bytes,9,opt,name=valid_ial,json=validIal,proto3" json:"valid_ial,omitempty"`
	ValidSignature       string   `protobuf:"bytes,10,opt,name=valid_signature,json=validSignature,proto3" json:"valid_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{14}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *Response) GetAal() float64 {
	if m != nil {
		return m.Aal
	}
	return 0
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Response) GetIdentityProof() string {
	if m != nil {
		return m.IdentityProof
	}
	return ""
}

func (m *Response) GetPrivateProofHash() string {
	if m != nil {
		return m.PrivateProofHash
	}
	return ""
}

func (m *Response) GetIdpId() string {
	if m != nil {
		return m.IdpId
	}
	return ""
}

func (m *Response) GetValidProof() string {
	if m != nil {
		return m.ValidProof
	}
	return ""
}

func (m *Response) GetValidIal() string {
	if m != nil {
		return m.ValidIal
	}
	return ""
}

func (m *Response) GetValidSignature() string {
	if m != nil {
		return m.ValidSignature
	}
	return ""
}

type ReportList struct {
	Reports              []*Report `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReportList) Reset()         { *m = ReportList{} }
func (m *ReportList) String() string { return proto.CompactTextString(m) }
func (*ReportList) ProtoMessage()    {}
func (*ReportList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{15}
}

func (m *ReportList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportList.Unmarshal(m, b)
}
func (m *ReportList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportList.Marshal(b, m, deterministic)
}
func (m *ReportList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportList.Merge(m, src)
}
func (m *ReportList) XXX_Size() int {
	return xxx_messageInfo_ReportList.Size(m)
}
func (m *ReportList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportList.DiscardUnknown(m)
}

var xxx_messageInfo_ReportList proto.InternalMessageInfo

func (m *ReportList) GetReports() []*Report {
	if m != nil {
		return m.Reports
	}
	return nil
}

type Report struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{16}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Report) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Report) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Accessor struct {
	AccessorId           string   `protobuf:"bytes,1,opt,name=accessor_id,json=accessorId,proto3" json:"accessor_id,omitempty"`
	AccessorType         string   `protobuf:"bytes,2,opt,name=accessor_type,json=accessorType,proto3" json:"accessor_type,omitempty"`
	AccessorPublicKey    string   `protobuf:"bytes,3,opt,name=accessor_public_key,json=accessorPublicKey,proto3" json:"accessor_public_key,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accessor) Reset()         { *m = Accessor{} }
func (m *Accessor) String() string { return proto.CompactTextString(m) }
func (*Accessor) ProtoMessage()    {}
func (*Accessor) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{17}
}

func (m *Accessor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accessor.Unmarshal(m, b)
}
func (m *Accessor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accessor.Marshal(b, m, deterministic)
}
func (m *Accessor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accessor.Merge(m, src)
}
func (m *Accessor) XXX_Size() int {
	return xxx_messageInfo_Accessor.Size(m)
}
func (m *Accessor) XXX_DiscardUnknown() {
	xxx_messageInfo_Accessor.DiscardUnknown(m)
}

var xxx_messageInfo_Accessor proto.InternalMessageInfo

func (m *Accessor) GetAccessorId() string {
	if m != nil {
		return m.AccessorId
	}
	return ""
}

func (m *Accessor) GetAccessorType() string {
	if m != nil {
		return m.AccessorType
	}
	return ""
}

func (m *Accessor) GetAccessorPublicKey() string {
	if m != nil {
		return m.AccessorPublicKey
	}
	return ""
}

func (m *Accessor) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Accessor) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type MsqDesList struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsqDesList) Reset()         { *m = MsqDesList{} }
func (m *MsqDesList) String() string { return proto.CompactTextString(m) }
func (*MsqDesList) ProtoMessage()    {}
func (*MsqDesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{18}
}

func (m *MsqDesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsqDesList.Unmarshal(m, b)
}
func (m *MsqDesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsqDesList.Marshal(b, m, deterministic)
}
func (m *MsqDesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsqDesList.Merge(m, src)
}
func (m *MsqDesList) XXX_Size() int {
	return xxx_messageInfo_MsqDesList.Size(m)
}
func (m *MsqDesList) XXX_DiscardUnknown() {
	xxx_messageInfo_MsqDesList.DiscardUnknown(m)
}

var xxx_messageInfo_MsqDesList proto.InternalMessageInfo

func (m *MsqDesList) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	First                bool     `protobuf:"varint,4,opt,name=first,proto3" json:"first,omitempty"`
	TimeoutBlock         int64    `protobuf:"varint,5,opt,name=timeout_block,json=timeoutBlock,proto3" json:"timeout_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{19}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *Node) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Node) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Node) GetFirst() bool {
	if m != nil {
		return m.First
	}
	return false
}

func (m *Node) GetTimeoutBlock() int64 {
	if m != nil {
		return m.TimeoutBlock
	}
	return 0
}

type ServiceList struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{20}
}

func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (m *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(m, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	ServiceId             string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MinIal                float64  `protobuf:"fixed64,2,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	MinAal                float64  `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	Active                bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Suspended             bool     `protobuf:"varint,5,opt,name=suspended,proto3" json:"suspended,omitempty"`
	AcceptedNamespaceList []string `protobuf:"bytes,6,rep,name=accepted_namespace_list,json=acceptedNamespaceList,proto3" json:"accepted_namespace_list,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{21}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Service) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *Service) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *Service) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Service) GetSuspended() bool {
	if m != nil {
		return m.Suspended
	}
	return false
}

func (m *Service) GetAcceptedNamespaceList() []string {
	if m != nil {
		return m.AcceptedNamespaceList
	}
	return nil
}

type ServiceDesList struct {
	Node                 []*ASNode `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServiceDesList) Reset()         { *m = ServiceDesList{} }
func (m *ServiceDesList) String() string { return proto.CompactTextString(m) }
func (*ServiceDesList) ProtoMessage()    {}
func (*ServiceDesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{22}
}

func (m *ServiceDesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDesList.Unmarshal(m, b)
}
func (m *ServiceDesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDesList.Marshal(b, m, deterministic)
}
func (m *ServiceDesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDesList.Merge(m, src)
}
func (m *ServiceDesList) XXX_Size() int {
	return xxx_messageInfo_ServiceDesList.Size(m)
}
func (m *ServiceDesList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDesList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDesList proto.InternalMessageInfo

func (m *ServiceDesList) GetNode() []*ASNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type ASNode struct {
	NodeId                string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MinIal                float64  `protobuf:"fixed64,2,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	MinAal                float64  `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	ServiceId             string   `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AcceptedNamespaceList []string `protobuf:"bytes,5,rep,name=accepted_namespace_list,json=acceptedNamespaceList,proto3" json:"accepted_namespace_list,omitempty"`
	Active                bool     `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ASNode) Reset()         { *m = ASNode{} }
func (m *ASNode) String() string { return proto.CompactTextString(m) }
func (*ASNode) ProtoMessage()    {}
func (*ASNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{23}
}

func (m *ASNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASNode.Unmarshal(m, b)
}
func (m *ASNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASNode.Marshal(b, m, deterministic)
}
func (m *ASNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASNode.Merge(m, src)
}
func (m *ASNode) XXX_Size() int {
	return xxx_messageInfo_ASNode.Size(m)
}
func (m *ASNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ASNode.DiscardUnknown(m)
}

var xxx_messageInfo_ASNode proto.InternalMessageInfo

func (m *ASNode) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ASNode) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *ASNode) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *ASNode) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ASNode) GetAcceptedNamespaceList() []string {
	if m != nil {
		return m.AcceptedNamespaceList
	}
	return nil
}

func (m *ASNode) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type RPList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPList) Reset()         { *m = RPList{} }
func (m *RPList) String() string { return proto.CompactTextString(m) }
func (*RPList) ProtoMessage()    {}
func (*RPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{24}
}

func (m *RPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPList.Unmarshal(m, b)
}
func (m *RPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPList.Marshal(b, m, deterministic)
}
func (m *RPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPList.Merge(m, src)
}
func (m *RPList) XXX_Size() int {
	return xxx_messageInfo_RPList.Size(m)
}
func (m *RPList) XXX_DiscardUnknown() {
	xxx_messageInfo_RPList.DiscardUnknown(m)
}

var xxx_messageInfo_RPList proto.InternalMessageInfo

func (m *RPList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type ASList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ASList) Reset()         { *m = ASList{} }
func (m *ASList) String() string { return proto.CompactTextString(m) }
func (*ASList) ProtoMessage()    {}
func (*ASList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{25}
}

func (m *ASList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASList.Unmarshal(m, b)
}
func (m *ASList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASList.Marshal(b, m, deterministic)
}
func (m *ASList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASList.Merge(m, src)
}
func (m *ASList) XXX_Size() int {
	return xxx_messageInfo_ASList.Size(m)
}
func (m *ASList) XXX_DiscardUnknown() {
	xxx_messageInfo_ASList.DiscardUnknown(m)
}

var xxx_messageInfo_ASList proto.InternalMessageInfo

func (m *ASList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type AllList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllList) Reset()         { *m = AllList{} }
func (m *AllList) String() string { return proto.CompactTextString(m) }
func (*AllList) ProtoMessage()    {}
func (*AllList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{26}
}

func (m *AllList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllList.Unmarshal(m, b)
}
func (m *AllList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllList.Marshal(b, m, deterministic)
}
func (m *AllList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllList.Merge(m, src)
}
func (m *AllList) XXX_Size() int {
	return xxx_messageInfo_AllList.Size(m)
}
func (m *AllList) XXX_DiscardUnknown() {
	xxx_messageInfo_AllList.DiscardUnknown(m)
}

var xxx_messageInfo_AllList proto.InternalMessageInfo

func (m *AllList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type AccessorInGroup struct {
	Accessors            []string `protobuf:"bytes,1,rep,name=accessors,proto3" json:"accessors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessorInGroup) Reset()         { *m = AccessorInGroup{} }
func (m *AccessorInGroup) String() string { return proto.CompactTextString(m) }
func (*AccessorInGroup) ProtoMessage()    {}
func (*AccessorInGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{27}
}

func (m *AccessorInGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessorInGroup.Unmarshal(m, b)
}
func (m *AccessorInGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessorInGroup.Marshal(b, m, deterministic)
}
func (m *AccessorInGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessorInGroup.Merge(m, src)
}
func (m *AccessorInGroup) XXX_Size() int {
	return xxx_messageInfo_AccessorInGroup.Size(m)
}
func (m *AccessorInGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessorInGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AccessorInGroup proto.InternalMessageInfo

func (m *AccessorInGroup) GetAccessors() []string {
	if m != nil {
		return m.Accessors
	}
	return nil
}

type Token struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{28}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TokenPrice struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenPrice) Reset()         { *m = TokenPrice{} }
func (m *TokenPrice) String() string { return proto.CompactTextString(m) }
func (*TokenPrice) ProtoMessage()    {}
func (*TokenPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{29}
}

func (m *TokenPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenPrice.Unmarshal(m, b)
}
func (m *TokenPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenPrice.Marshal(b, m, deterministic)
}
func (m *TokenPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenPrice.Merge(m, src)
}
func (m *TokenPrice) XXX_Size() int {
	return xxx_messageInfo_TokenPrice.Size(m)
}
func (m *TokenPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenPrice.DiscardUnknown(m)
}

var xxx_messageInfo_TokenPrice proto.InternalMessageInfo

func (m *TokenPrice) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ReferenceGroup struct {
	Identities           []*IdentityInRefGroup `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	Idps                 []*IdPInRefGroup      `protobuf:"bytes,2,rep,name=idps,proto3" json:"idps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReferenceGroup) Reset()         { *m = ReferenceGroup{} }
func (m *ReferenceGroup) String() string { return proto.CompactTextString(m) }
func (*ReferenceGroup) ProtoMessage()    {}
func (*ReferenceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{30}
}

func (m *ReferenceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceGroup.Unmarshal(m, b)
}
func (m *ReferenceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceGroup.Marshal(b, m, deterministic)
}
func (m *ReferenceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceGroup.Merge(m, src)
}
func (m *ReferenceGroup) XXX_Size() int {
	return xxx_messageInfo_ReferenceGroup.Size(m)
}
func (m *ReferenceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceGroup proto.InternalMessageInfo

func (m *ReferenceGroup) GetIdentities() []*IdentityInRefGroup {
	if m != nil {
		return m.Identities
	}
	return nil
}

func (m *ReferenceGroup) GetIdps() []*IdPInRefGroup {
	if m != nil {
		return m.Idps
	}
	return nil
}

type IdPInRefGroup struct {
	NodeId               string      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode                 []int64     `protobuf:"varint,2,rep,packed,name=mode,proto3" json:"mode,omitempty"`
	Accessors            []*Accessor `protobuf:"bytes,3,rep,name=accessors,proto3" json:"accessors,omitempty"`
	Ial                  float64     `protobuf:"fixed64,4,opt,name=ial,proto3" json:"ial,omitempty"`
	Active               bool        `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IdPInRefGroup) Reset()         { *m = IdPInRefGroup{} }
func (m *IdPInRefGroup) String() string { return proto.CompactTextString(m) }
func (*IdPInRefGroup) ProtoMessage()    {}
func (*IdPInRefGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{31}
}

func (m *IdPInRefGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdPInRefGroup.Unmarshal(m, b)
}
func (m *IdPInRefGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdPInRefGroup.Marshal(b, m, deterministic)
}
func (m *IdPInRefGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdPInRefGroup.Merge(m, src)
}
func (m *IdPInRefGroup) XXX_Size() int {
	return xxx_messageInfo_IdPInRefGroup.Size(m)
}
func (m *IdPInRefGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_IdPInRefGroup.DiscardUnknown(m)
}

var xxx_messageInfo_IdPInRefGroup proto.InternalMessageInfo

func (m *IdPInRefGroup) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *IdPInRefGroup) GetMode() []int64 {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (m *IdPInRefGroup) GetAccessors() []*Accessor {
	if m != nil {
		return m.Accessors
	}
	return nil
}

func (m *IdPInRefGroup) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *IdPInRefGroup) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type IdentityInRefGroup struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	IdentifierHash       string   `protobuf:"bytes,2,opt,name=identifier_hash,json=identifierHash,proto3" json:"identifier_hash,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityInRefGroup) Reset()         { *m = IdentityInRefGroup{} }
func (m *IdentityInRefGroup) String() string { return proto.CompactTextString(m) }
func (*IdentityInRefGroup) ProtoMessage()    {}
func (*IdentityInRefGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{32}
}

func (m *IdentityInRefGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityInRefGroup.Unmarshal(m, b)
}
func (m *IdentityInRefGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityInRefGroup.Marshal(b, m, deterministic)
}
func (m *IdentityInRefGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityInRefGroup.Merge(m, src)
}
func (m *IdentityInRefGroup) XXX_Size() int {
	return xxx_messageInfo_IdentityInRefGroup.Size(m)
}
func (m *IdentityInRefGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityInRefGroup.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityInRefGroup proto.InternalMessageInfo

func (m *IdentityInRefGroup) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *IdentityInRefGroup) GetIdentifierHash() string {
	if m != nil {
		return m.IdentifierHash
	}
	return ""
}

func (m *IdentityInRefGroup) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type AllowedModeList struct {
	Mode                 []int64  `protobuf:"varint,1,rep,packed,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowedModeList) Reset()         { *m = AllowedModeList{} }
func (m *AllowedModeList) String() string { return proto.CompactTextString(m) }
func (*AllowedModeList) ProtoMessage()    {}
func (*AllowedModeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{33}
}

func (m *AllowedModeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowedModeList.Unmarshal(m, b)
}
func (m *AllowedModeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowedModeList.Marshal(b, m, deterministic)
}
func (m *AllowedModeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowedModeList.Merge(m, src)
}
func (m *AllowedModeList) XXX_Size() int {
	return xxx_messageInfo_AllowedModeList.Size(m)
}
func (m *AllowedModeList) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowedModeList.DiscardUnknown(m)
}

var xxx_messageInfo_AllowedModeList proto.InternalMessageInfo

func (m *AllowedModeList) GetMode() []int64 {
	if m != nil {
		return m.Mode
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyVersions)(nil), "KeyVersions")
	proto.RegisterType((*NodeDetail)(nil), "NodeDetail")
	proto.RegisterType((*MQ)(nil), "MQ")
	proto.RegisterType((*IdPList)(nil), "IdPList")
	proto.RegisterType((*NamespaceList)(nil), "NamespaceList")
	proto.RegisterType((*Namespace)(nil), "Namespace")
	proto.RegisterType((*ServiceDetailList)(nil), "ServiceDetailList")
	proto.RegisterType((*ServiceDetail)(nil), "ServiceDetail")
	proto.RegisterType((*ApproveService)(nil), "ApproveService")
	proto.RegisterType((*TimeOutBlockRegisterIdentity)(nil), "TimeOutBlockRegisterIdentity")
	proto.RegisterType((*Proxy)(nil), "Proxy")
	proto.RegisterType((*BehindNodeList)(nil), "BehindNodeList")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ReportList)(nil), "ReportList")
	proto.RegisterType((*Report)(nil), "Report")
	proto.RegisterType((*Accessor)(nil), "Accessor")
	proto.RegisterType((*MsqDesList)(nil), "MsqDesList")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*ServiceList)(nil), "ServiceList")
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*ServiceDesList)(nil), "ServiceDesList")
	proto.RegisterType((*ASNode)(nil), "ASNode")
	proto.RegisterType((*RPList)(nil), "RPList")
	proto.RegisterType((*ASList)(nil), "ASList")
	proto.RegisterType((*AllList)(nil), "AllList")
	proto.RegisterType((*AccessorInGroup)(nil), "AccessorInGroup")
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*TokenPrice)(nil), "TokenPrice")
	proto.RegisterType((*ReferenceGroup)(nil), "ReferenceGroup")
	proto.RegisterType((*IdPInRefGroup)(nil), "IdPInRefGroup")
	proto.RegisterType((*IdentityInRefGroup)(nil), "IdentityInRefGroup")
	proto.RegisterType((*AllowedModeList)(nil), "AllowedModeList")
}

func init() { proto.RegisterFile("protos/data/data.proto", fileDescriptor_492be2f0ffbab25c) }

var fileDescriptor_492be2f0ffbab25c = []byte{
	// 1587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xcd, 0x6f, 0x14, 0xc7,
	0x12, 0xd7, 0xec, 0xf7, 0xd6, 0x7a, 0xd7, 0xf6, 0x18, 0xc3, 0xbc, 0x07, 0xef, 0x61, 0xcf, 0x83,
	0x87, 0x41, 0x61, 0x89, 0x8c, 0x12, 0x45, 0xca, 0x21, 0x5a, 0xb0, 0x12, 0x36, 0xc4, 0x60, 0xc6,
	0x56, 0xae, 0xa3, 0x66, 0xba, 0xed, 0x6d, 0x31, 0x5f, 0x9e, 0x9e, 0x35, 0xf8, 0x9e, 0x7b, 0xfe,
	0x13, 0xae, 0x91, 0x22, 0xe5, 0x92, 0x53, 0xfe, 0xa3, 0x5c, 0xa3, 0xaa, 0xee, 0x9e, 0x9d, 0x8d,
	0xb1, 0xad, 0x5c, 0xac, 0xae, 0x5f, 0xd5, 0xb8, 0xbb, 0xaa, 0x7e, 0xf5, 0xb1, 0x70, 0x33, 0x2f,
	0xb2, 0x32, 0x53, 0x4f, 0x38, 0x2b, 0x19, 0xfd, 0x19, 0x13, 0xe0, 0x3f, 0x84, 0xc1, 0x4b, 0x71,
	0xfe, 0xa3, 0x28, 0x94, 0xcc, 0x52, 0xe5, 0xfe, 0x1b, 0x7a, 0x67, 0xe6, 0xec, 0x39, 0x5b, 0xcd,
	0x9d, 0x66, 0x50, 0xc9, 0xfe, 0xc7, 0x06, 0xc0, 0xab, 0x8c, 0x8b, 0x3d, 0x51, 0x32, 0x19, 0xbb,
	0xff, 0x01, 0xc8, 0xe7, 0x6f, 0x63, 0x19, 0x85, 0xef, 0xc4, 0xb9, 0xe7, 0x6c, 0x39, 0x3b, 0xfd,
	0xa0, 0xaf, 0x91, 0x97, 0xe2, 0xdc, 0x7d, 0x04, 0xeb, 0x09, 0x53, 0xa5, 0x28, 0xc2, 0x9a, 0x55,
	0x83, 0xac, 0x56, 0xb5, 0xe2, 0xa0, 0xb2, 0xbd, 0x0d, 0xfd, 0x34, 0xe3, 0x22, 0x4c, 0x59, 0x22,
	0xbc, 0x26, 0xd9, 0xf4, 0x10, 0x78, 0xc5, 0x12, 0xe1, 0xba, 0xd0, 0x2a, 0xb2, 0x58, 0x78, 0x2d,
	0xc2, 0xe9, 0xec, 0xde, 0x82, 0x6e, 0xc2, 0x3e, 0x84, 0x92, 0xc5, 0x5e, 0x7b, 0xcb, 0xd9, 0x71,
	0x82, 0x4e, 0xc2, 0x3e, 0x4c, 0x59, 0x6c, 0x15, 0x8c, 0xc5, 0x5e, 0xa7, 0x52, 0x4c, 0x58, 0xec,
	0x6e, 0x40, 0x23, 0x39, 0xf5, 0xba, 0x5b, 0xcd, 0x9d, 0xc1, 0x6e, 0x73, 0xbc, 0xff, 0x26, 0x68,
	0x24, 0xa7, 0xee, 0x4d, 0xe8, 0xb0, 0xa8, 0x94, 0x67, 0xc2, 0xeb, 0x6d, 0x39, 0x3b, 0xbd, 0xc0,
	0x48, 0xae, 0x0f, 0xc3, 0xbc, 0xc8, 0x3e, 0x9c, 0x87, 0xf4, 0x2a, 0xc9, 0xbd, 0x3e, 0xdd, 0x3d,
	0x20, 0x10, 0x43, 0x30, 0xe5, 0xee, 0x36, 0xac, 0x68, 0x9b, 0x28, 0x4b, 0x8f, 0xe5, 0x89, 0x07,
	0x35, 0x93, 0xe7, 0x04, 0xf9, 0x3b, 0xd0, 0xd8, 0x7f, 0xe3, 0x8e, 0xa0, 0x21, 0x73, 0x13, 0x9f,
	0x86, 0xcc, 0xd1, 0x9f, 0x3c, 0x2b, 0x4a, 0x8a, 0x45, 0x33, 0xa0, 0xb3, 0xef, 0x43, 0x77, 0xca,
	0x0f, 0x7e, 0x90, 0xaa, 0x44, 0x0f, 0xec, 0xad, 0x98, 0x80, 0x7e, 0xd0, 0x49, 0xe9, 0x42, 0xff,
	0x6b, 0x18, 0x62, 0x3c, 0x54, 0xce, 0x22, 0x41, 0x96, 0x8f, 0x00, 0x52, 0x0b, 0xe8, 0x6c, 0x0d,
	0x76, 0x61, 0x5c, 0xd9, 0x04, 0x35, 0xad, 0x1f, 0x41, 0xbf, 0x52, 0xb8, 0x77, 0xa0, 0x5f, 0xa9,
	0x6c, 0xe2, 0x2a, 0xc0, 0xdd, 0x82, 0x01, 0x17, 0x2a, 0x2a, 0x64, 0x5e, 0xca, 0x2c, 0x35, 0x29,
	0xab, 0x43, 0xb5, 0xb0, 0x35, 0xeb, 0x61, 0xf3, 0xbf, 0x81, 0xf5, 0x43, 0x51, 0x9c, 0xc9, 0xc8,
	0x50, 0xc4, 0xbc, 0xb2, 0xa7, 0x34, 0x68, 0xdf, 0x38, 0x1a, 0x2f, 0x59, 0x05, 0x95, 0xde, 0xff,
	0xd5, 0x81, 0xe1, 0x92, 0x0e, 0x49, 0x66, 0xb4, 0x3a, 0x20, 0xf4, 0x56, 0x83, 0xe8, 0x24, 0x58,
	0x35, 0x71, 0xc7, 0x3c, 0xd6, 0x60, 0x44, 0x9f, 0xbb, 0x30, 0x40, 0xba, 0x87, 0x2a, 0x9a, 0x89,
	0x84, 0x19, 0x76, 0x01, 0x42, 0x87, 0x84, 0xb8, 0x63, 0xd8, 0xa8, 0x19, 0x84, 0x86, 0xee, 0x86,
	0x6e, 0xeb, 0x0b, 0x43, 0x53, 0x23, 0x35, 0xef, 0xdb, 0x4b, 0xde, 0xef, 0xc0, 0x68, 0x92, 0xe7,
	0x45, 0x76, 0x26, 0x8c, 0x0b, 0x35, 0x4b, 0x67, 0xc9, 0x72, 0x0f, 0xee, 0x1c, 0xc9, 0x44, 0xbc,
	0x9e, 0x97, 0xcf, 0xe2, 0x2c, 0x7a, 0x17, 0x88, 0x13, 0x89, 0xf5, 0x30, 0xe5, 0x22, 0x2d, 0x65,
	0x79, 0xee, 0xde, 0x83, 0x51, 0x29, 0x13, 0x11, 0x66, 0xf3, 0x32, 0x7c, 0x8b, 0x16, 0xf4, 0x7d,
	0x33, 0x58, 0x29, 0x6b, 0x5f, 0xf9, 0xcf, 0xa1, 0x7d, 0x80, 0x64, 0xbb, 0xc8, 0x56, 0xe7, 0x22,
	0x5b, 0x6f, 0x42, 0xc7, 0xf0, 0x54, 0x87, 0xc8, 0x48, 0xfe, 0xff, 0x61, 0xf4, 0x4c, 0xcc, 0x64,
	0xca, 0xd1, 0x8e, 0xf2, 0x75, 0x03, 0xda, 0xf8, 0x7f, 0x94, 0x61, 0x9f, 0x16, 0xfc, 0xdf, 0x5a,
	0xd0, 0x0d, 0xc4, 0xe9, 0x5c, 0xa8, 0x12, 0x73, 0x52, 0xe8, 0x63, 0x2d, 0x27, 0x06, 0x99, 0x72,
	0x2a, 0x41, 0x99, 0x86, 0x92, 0xe7, 0x86, 0xe2, 0x9d, 0x44, 0xa6, 0x53, 0x9e, 0x5b, 0x05, 0xd6,
	0x66, 0xd3, 0xd4, 0xa6, 0x4c, 0x27, 0xa6, 0x68, 0xf1, 0x0b, 0x16, 0x53, 0xd4, 0xb5, 0x02, 0xab,
	0xf9, 0x01, 0xac, 0xda, 0x9b, 0xd0, 0xf5, 0x6c, 0x5e, 0x52, 0xcc, 0x9b, 0xc1, 0xc8, 0xc0, 0x47,
	0x1a, 0x75, 0xff, 0x0b, 0x03, 0xc9, 0xf3, 0x50, 0xf2, 0x30, 0x96, 0xaa, 0xf4, 0x3a, 0xf4, 0xf4,
	0xbe, 0xe4, 0xf9, 0x94, 0x93, 0x53, 0x5f, 0x01, 0x25, 0x32, 0xb4, 0xff, 0x8d, 0xac, 0x74, 0x33,
	0x58, 0x19, 0xef, 0xb1, 0x92, 0x19, 0xdf, 0x82, 0x55, 0xbe, 0x10, 0xe8, 0xcb, 0xcf, 0xe1, 0x86,
	0xfd, 0x28, 0x11, 0x4a, 0xb1, 0x13, 0x11, 0xce, 0x98, 0x9a, 0x51, 0xc3, 0xe8, 0x07, 0xae, 0xd1,
	0xed, 0x6b, 0xd5, 0x0b, 0xa6, 0x66, 0xee, 0x18, 0x86, 0x85, 0x50, 0x79, 0x96, 0x2a, 0xa1, 0xef,
	0xe9, 0xd3, 0x3d, 0xfd, 0x71, 0x60, 0xd0, 0x60, 0xc5, 0xea, 0xe9, 0x06, 0x4c, 0x4d, 0x9c, 0x29,
	0xc1, 0xa9, 0x85, 0xf4, 0x02, 0x23, 0x61, 0x53, 0x44, 0xa7, 0x39, 0xd2, 0xc0, 0x1b, 0x90, 0xaa,
	0x47, 0xc0, 0xeb, 0x79, 0xe9, 0x7a, 0xd0, 0xcd, 0xe7, 0x45, 0x9e, 0x29, 0xe1, 0xad, 0xd0, 0x4b,
	0xac, 0x88, 0xf9, 0xcb, 0xde, 0xa7, 0xa2, 0xf0, 0x86, 0x84, 0x6b, 0x01, 0x9b, 0x4e, 0x92, 0x71,
	0xe1, 0x8d, 0x74, 0xd3, 0xc1, 0x33, 0x5e, 0x30, 0x57, 0x22, 0x8c, 0xb2, 0x79, 0x5a, 0x7a, 0xab,
	0xa4, 0xe8, 0xcd, 0x95, 0x78, 0x8e, 0xb2, 0xbb, 0x0b, 0x9b, 0x51, 0x21, 0x18, 0xd6, 0xbb, 0xe6,
	0x60, 0x38, 0x13, 0xf2, 0x64, 0x56, 0x7a, 0x6b, 0x64, 0xb8, 0x61, 0x95, 0xc4, 0xc5, 0x17, 0xa4,
	0x72, 0xff, 0x05, 0xbd, 0x68, 0xc6, 0x28, 0xf7, 0xde, 0xba, 0x7e, 0x15, 0xc9, 0x53, 0xee, 0xff,
	0xe9, 0xc0, 0xa0, 0x16, 0xe7, 0xeb, 0xea, 0xfa, 0x0e, 0x00, 0x53, 0x55, 0x3a, 0x1b, 0x94, 0xce,
	0x1e, 0x53, 0x26, 0x9b, 0x9b, 0xd0, 0x21, 0x22, 0x29, 0xe2, 0x51, 0x33, 0x68, 0x23, 0x8f, 0x14,
	0x16, 0xb2, 0x4d, 0x55, 0xce, 0x0a, 0x96, 0x28, 0x9d, 0x29, 0x53, 0xc8, 0x46, 0x75, 0x40, 0x1a,
	0x4a, 0xd4, 0x63, 0xd8, 0x60, 0xa9, 0x7a, 0x2f, 0x0a, 0xc1, 0xc3, 0xda, 0x6d, 0x6d, 0xba, 0x6d,
	0xcd, 0xaa, 0x26, 0xf6, 0xd6, 0x2f, 0xe0, 0x56, 0x21, 0x22, 0x21, 0xcf, 0x04, 0x0f, 0x89, 0x4c,
	0xc7, 0x45, 0x96, 0xd4, 0xf9, 0x76, 0xc3, 0xaa, 0xd1, 0xd1, 0x6f, 0x8b, 0x2c, 0xc1, 0xcf, 0xfc,
	0x5f, 0x1a, 0xd0, 0xb3, 0x99, 0x77, 0xd7, 0xa0, 0x89, 0x2c, 0x77, 0x88, 0xe5, 0x78, 0x44, 0x04,
	0x0b, 0xa2, 0xa1, 0x11, 0xc6, 0x62, 0xe4, 0x83, 0x2a, 0x59, 0x39, 0x57, 0xa6, 0x57, 0x19, 0x09,
	0xbb, 0xb6, 0x92, 0x27, 0x29, 0x2b, 0xe7, 0x85, 0x1d, 0x86, 0x0b, 0xc0, 0xbd, 0x0f, 0x23, 0x69,
	0xfa, 0x47, 0x98, 0x17, 0x59, 0x76, 0x4c, 0x95, 0xd2, 0x0f, 0x86, 0x16, 0x3d, 0x40, 0xd0, 0xfd,
	0x0c, 0xdc, 0xbc, 0x90, 0x67, 0xac, 0x14, 0xda, 0x4a, 0x87, 0xa8, 0x43, 0xa6, 0x6b, 0x46, 0x43,
	0x96, 0x14, 0xa1, 0x4d, 0xe8, 0xe8, 0xb2, 0xf2, 0xba, 0x9a, 0x4c, 0x54, 0x51, 0xd8, 0x52, 0xcf,
	0x58, 0x2c, 0xb9, 0xb9, 0x48, 0x97, 0x02, 0x10, 0xa4, 0x6f, 0xb9, 0x0d, 0x7d, 0x6d, 0x80, 0xce,
	0xea, 0xd9, 0xd9, 0x23, 0xc0, 0x14, 0xb5, 0x56, 0x2e, 0xbc, 0xd1, 0xb3, 0x73, 0x44, 0xf0, 0xa1,
	0x45, 0xfd, 0x27, 0x00, 0x81, 0xc0, 0xf1, 0x48, 0xe1, 0xdf, 0x86, 0x6e, 0x41, 0x92, 0x1d, 0x23,
	0xdd, 0xb1, 0xd6, 0x06, 0x16, 0xf7, 0xbf, 0x87, 0x8e, 0x86, 0x30, 0x86, 0x89, 0x28, 0x67, 0x99,
	0xa5, 0x96, 0x91, 0xb0, 0x38, 0xf2, 0x42, 0x46, 0xc2, 0xc4, 0x5b, 0x0b, 0x58, 0x1c, 0x98, 0x50,
	0x13, 0x6f, 0x3a, 0xfb, 0x1f, 0x1d, 0xe8, 0x4d, 0xa2, 0x48, 0x28, 0x95, 0x15, 0xe8, 0x30, 0x33,
	0xe7, 0x05, 0x5d, 0xc1, 0x42, 0x53, 0xee, 0xfe, 0x0f, 0x86, 0x95, 0x41, 0x79, 0x9e, 0xdb, 0x41,
	0xb4, 0x62, 0xc1, 0xa3, 0xf3, 0x5c, 0x20, 0x3f, 0x2b, 0xa3, 0xda, 0x4e, 0xa4, 0x6f, 0x5d, 0xb7,
	0xaa, 0xc5, 0x56, 0xb4, 0x18, 0x1f, 0xad, 0xa5, 0xed, 0xa4, 0xaa, 0xf0, 0x76, 0xad, 0xc2, 0xfd,
	0x87, 0x00, 0xfb, 0xea, 0x74, 0x4f, 0x28, 0x8a, 0xd6, 0xed, 0x7a, 0x17, 0x1f, 0xec, 0xb6, 0xc7,
	0xd8, 0xdf, 0x6d, 0x33, 0xff, 0xc9, 0x81, 0x16, 0xca, 0x9f, 0xa0, 0x63, 0x6d, 0xfb, 0x30, 0x83,
	0x22, 0xad, 0x06, 0xc8, 0xa7, 0x66, 0x3e, 0x3e, 0xe6, 0x58, 0x16, 0xaa, 0x34, 0x6f, 0xd4, 0x02,
	0xc6, 0xc3, 0x34, 0x6c, 0x33, 0xc0, 0xda, 0x8b, 0x01, 0x96, 0xd9, 0x01, 0xf6, 0x14, 0x06, 0x66,
	0x52, 0xd2, 0x93, 0xef, 0x5d, 0x58, 0x14, 0x7a, 0x76, 0x51, 0xa8, 0xad, 0x08, 0x7f, 0x38, 0xd0,
	0xb5, 0xf3, 0xf5, 0x9a, 0x26, 0x52, 0x1b, 0x2b, 0x8d, 0xa5, 0xb1, 0x72, 0xe9, 0x20, 0xba, 0x2c,
	0xe2, 0x58, 0x7a, 0x73, 0x95, 0x8b, 0x94, 0x0b, 0x6e, 0xa6, 0xfe, 0x02, 0x70, 0xbf, 0x84, 0x5b,
	0x98, 0xbc, 0xbc, 0x14, 0x3c, 0xac, 0xd6, 0xa8, 0x7a, 0x63, 0xd8, 0xb4, 0xea, 0xa5, 0xfd, 0xcd,
	0x7f, 0x0c, 0xa3, 0x6a, 0xd9, 0xb1, 0x59, 0x6b, 0x61, 0xb8, 0x2b, 0x82, 0x4f, 0x0e, 0x29, 0x6d,
	0x04, 0xfa, 0xbf, 0x3b, 0xd0, 0xd1, 0xc0, 0xf2, 0x8e, 0x58, 0xcf, 0xd2, 0x3f, 0x77, 0x79, 0x39,
	0x86, 0xad, 0xbf, 0xc7, 0xf0, 0x0a, 0xdf, 0xda, 0x57, 0xf8, 0x56, 0x8b, 0x64, 0x67, 0x69, 0xf5,
	0xd9, 0x86, 0x4e, 0x70, 0xcd, 0x9e, 0xbb, 0x8d, 0x6e, 0x5e, 0x6d, 0xe2, 0x43, 0x77, 0x12, 0xc7,
	0x57, 0xdb, 0x3c, 0x81, 0x55, 0x5b, 0xbf, 0xd3, 0xf4, 0xbb, 0x22, 0x9b, 0xe7, 0x98, 0x46, 0x5b,
	0x65, 0x76, 0xbd, 0x59, 0x00, 0xfe, 0x5d, 0x68, 0x1f, 0x65, 0xef, 0x84, 0x5e, 0xf0, 0x12, 0x1a,
	0x8a, 0xba, 0x30, 0x8c, 0xe4, 0xfb, 0x00, 0x64, 0x70, 0x40, 0x4d, 0xa3, 0x6a, 0x25, 0x4e, 0xad,
	0x95, 0xf8, 0x12, 0x46, 0x81, 0x38, 0x16, 0x85, 0x48, 0x23, 0xa1, 0x2f, 0x7d, 0x0a, 0x60, 0x5a,
	0xb0, 0xac, 0x88, 0xbd, 0x31, 0xb6, 0xbb, 0xde, 0x34, 0x0d, 0xc4, 0x31, 0x19, 0x06, 0x35, 0x33,
	0xd7, 0x87, 0x96, 0xe4, 0xb9, 0xa2, 0xc9, 0x87, 0x0b, 0xf3, 0x94, 0x1f, 0xd4, 0x2c, 0x49, 0xe7,
	0xff, 0xec, 0xc0, 0x70, 0x09, 0xbf, 0x9c, 0x16, 0x76, 0xfa, 0x37, 0xe8, 0x17, 0x9d, 0x9e, 0xfe,
	0x0f, 0xea, 0xc1, 0x68, 0x9a, 0x15, 0xc5, 0x46, 0xac, 0x16, 0x17, 0xdb, 0x24, 0x5a, 0x8b, 0x26,
	0x71, 0xd9, 0x06, 0xac, 0xc0, 0xbd, 0xe8, 0xd7, 0x35, 0xbf, 0x36, 0x1e, 0xc0, 0xaa, 0xf6, 0xfb,
	0x58, 0x8a, 0x42, 0x4f, 0x23, 0xdd, 0x78, 0x46, 0x0b, 0x98, 0x66, 0xd1, 0x65, 0x3f, 0x3a, 0xee,
	0xc3, 0xea, 0x24, 0x8e, 0xb3, 0xf7, 0x82, 0xef, 0xdb, 0x15, 0xd6, 0xba, 0xeb, 0x2c, 0xdc, 0x7d,
	0xdb, 0xa1, 0x9f, 0xbb, 0x4f, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x52, 0x54, 0x37, 0x6b, 0x08,
	0x0f, 0x00, 0x00,
}
