// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/data/data.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyVersions struct {
	Versions             []int64  `protobuf:"varint,1,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyVersions) Reset()         { *m = KeyVersions{} }
func (m *KeyVersions) String() string { return proto.CompactTextString(m) }
func (*KeyVersions) ProtoMessage()    {}
func (*KeyVersions) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{0}
}

func (m *KeyVersions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyVersions.Unmarshal(m, b)
}
func (m *KeyVersions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyVersions.Marshal(b, m, deterministic)
}
func (m *KeyVersions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyVersions.Merge(m, src)
}
func (m *KeyVersions) XXX_Size() int {
	return xxx_messageInfo_KeyVersions.Size(m)
}
func (m *KeyVersions) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyVersions.DiscardUnknown(m)
}

var xxx_messageInfo_KeyVersions proto.InternalMessageInfo

func (m *KeyVersions) GetVersions() []int64 {
	if m != nil {
		return m.Versions
	}
	return nil
}

type NodeDetail struct {
	PublicKey                              string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MasterPublicKey                        string   `protobuf:"bytes,2,opt,name=master_public_key,json=masterPublicKey,proto3" json:"master_public_key,omitempty"`
	NodeName                               string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role                                   string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	MaxIal                                 float64  `protobuf:"fixed64,5,opt,name=max_ial,json=maxIal,proto3" json:"max_ial,omitempty"`
	MaxAal                                 float64  `protobuf:"fixed64,6,opt,name=max_aal,json=maxAal,proto3" json:"max_aal,omitempty"`
	Mq                                     []*MQ    `protobuf:"bytes,7,rep,name=mq,proto3" json:"mq,omitempty"`
	Active                                 bool     `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	ProxyNodeId                            string   `protobuf:"bytes,9,opt,name=proxy_node_id,json=proxyNodeId,proto3" json:"proxy_node_id,omitempty"`
	ProxyConfig                            string   `protobuf:"bytes,10,opt,name=proxy_config,json=proxyConfig,proto3" json:"proxy_config,omitempty"`
	SupportedRequestMessageDataUrlTypeList []string `protobuf:"bytes,11,rep,name=supported_request_message_data_url_type_list,json=supportedRequestMessageDataUrlTypeList,proto3" json:"supported_request_message_data_url_type_list,omitempty"`
	XXX_NoUnkeyedLiteral                   struct{} `json:"-"`
	XXX_unrecognized                       []byte   `json:"-"`
	XXX_sizecache                          int32    `json:"-"`
}

func (m *NodeDetail) Reset()         { *m = NodeDetail{} }
func (m *NodeDetail) String() string { return proto.CompactTextString(m) }
func (*NodeDetail) ProtoMessage()    {}
func (*NodeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{1}
}

func (m *NodeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDetail.Unmarshal(m, b)
}
func (m *NodeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDetail.Marshal(b, m, deterministic)
}
func (m *NodeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDetail.Merge(m, src)
}
func (m *NodeDetail) XXX_Size() int {
	return xxx_messageInfo_NodeDetail.Size(m)
}
func (m *NodeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDetail proto.InternalMessageInfo

func (m *NodeDetail) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *NodeDetail) GetMasterPublicKey() string {
	if m != nil {
		return m.MasterPublicKey
	}
	return ""
}

func (m *NodeDetail) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeDetail) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *NodeDetail) GetMaxIal() float64 {
	if m != nil {
		return m.MaxIal
	}
	return 0
}

func (m *NodeDetail) GetMaxAal() float64 {
	if m != nil {
		return m.MaxAal
	}
	return 0
}

func (m *NodeDetail) GetMq() []*MQ {
	if m != nil {
		return m.Mq
	}
	return nil
}

func (m *NodeDetail) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *NodeDetail) GetProxyNodeId() string {
	if m != nil {
		return m.ProxyNodeId
	}
	return ""
}

func (m *NodeDetail) GetProxyConfig() string {
	if m != nil {
		return m.ProxyConfig
	}
	return ""
}

func (m *NodeDetail) GetSupportedRequestMessageDataUrlTypeList() []string {
	if m != nil {
		return m.SupportedRequestMessageDataUrlTypeList
	}
	return nil
}

type MQ struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MQ) Reset()         { *m = MQ{} }
func (m *MQ) String() string { return proto.CompactTextString(m) }
func (*MQ) ProtoMessage()    {}
func (*MQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{2}
}

func (m *MQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MQ.Unmarshal(m, b)
}
func (m *MQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MQ.Marshal(b, m, deterministic)
}
func (m *MQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MQ.Merge(m, src)
}
func (m *MQ) XXX_Size() int {
	return xxx_messageInfo_MQ.Size(m)
}
func (m *MQ) XXX_DiscardUnknown() {
	xxx_messageInfo_MQ.DiscardUnknown(m)
}

var xxx_messageInfo_MQ proto.InternalMessageInfo

func (m *MQ) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *MQ) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type IdPList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdPList) Reset()         { *m = IdPList{} }
func (m *IdPList) String() string { return proto.CompactTextString(m) }
func (*IdPList) ProtoMessage()    {}
func (*IdPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{3}
}

func (m *IdPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdPList.Unmarshal(m, b)
}
func (m *IdPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdPList.Marshal(b, m, deterministic)
}
func (m *IdPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdPList.Merge(m, src)
}
func (m *IdPList) XXX_Size() int {
	return xxx_messageInfo_IdPList.Size(m)
}
func (m *IdPList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdPList.DiscardUnknown(m)
}

var xxx_messageInfo_IdPList proto.InternalMessageInfo

func (m *IdPList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type NamespaceList struct {
	Namespaces           []*Namespace `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NamespaceList) Reset()         { *m = NamespaceList{} }
func (m *NamespaceList) String() string { return proto.CompactTextString(m) }
func (*NamespaceList) ProtoMessage()    {}
func (*NamespaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{4}
}

func (m *NamespaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceList.Unmarshal(m, b)
}
func (m *NamespaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceList.Marshal(b, m, deterministic)
}
func (m *NamespaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceList.Merge(m, src)
}
func (m *NamespaceList) XXX_Size() int {
	return xxx_messageInfo_NamespaceList.Size(m)
}
func (m *NamespaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceList.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceList proto.InternalMessageInfo

func (m *NamespaceList) GetNamespaces() []*Namespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

type Namespace struct {
	Namespace                                    string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Description                                  string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Active                                       bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	AllowedIdentifierCountInReferenceGroup       int32    `protobuf:"varint,4,opt,name=allowed_identifier_count_in_reference_group,json=allowedIdentifierCountInReferenceGroup,proto3" json:"allowed_identifier_count_in_reference_group,omitempty"`
	AllowedActiveIdentifierCountInReferenceGroup int32    `protobuf:"varint,5,opt,name=allowed_active_identifier_count_in_reference_group,json=allowedActiveIdentifierCountInReferenceGroup,proto3" json:"allowed_active_identifier_count_in_reference_group,omitempty"`
	XXX_NoUnkeyedLiteral                         struct{} `json:"-"`
	XXX_unrecognized                             []byte   `json:"-"`
	XXX_sizecache                                int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{5}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Namespace) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Namespace) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Namespace) GetAllowedIdentifierCountInReferenceGroup() int32 {
	if m != nil {
		return m.AllowedIdentifierCountInReferenceGroup
	}
	return 0
}

func (m *Namespace) GetAllowedActiveIdentifierCountInReferenceGroup() int32 {
	if m != nil {
		return m.AllowedActiveIdentifierCountInReferenceGroup
	}
	return 0
}

type ServiceDetailList struct {
	Services             []*ServiceDetail `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServiceDetailList) Reset()         { *m = ServiceDetailList{} }
func (m *ServiceDetailList) String() string { return proto.CompactTextString(m) }
func (*ServiceDetailList) ProtoMessage()    {}
func (*ServiceDetailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{6}
}

func (m *ServiceDetailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDetailList.Unmarshal(m, b)
}
func (m *ServiceDetailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDetailList.Marshal(b, m, deterministic)
}
func (m *ServiceDetailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDetailList.Merge(m, src)
}
func (m *ServiceDetailList) XXX_Size() int {
	return xxx_messageInfo_ServiceDetailList.Size(m)
}
func (m *ServiceDetailList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDetailList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDetailList proto.InternalMessageInfo

func (m *ServiceDetailList) GetServices() []*ServiceDetail {
	if m != nil {
		return m.Services
	}
	return nil
}

type ServiceDetail struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName          string   `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	DataSchema           string   `protobuf:"bytes,3,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`
	DataSchemaVersion    string   `protobuf:"bytes,4,opt,name=data_schema_version,json=dataSchemaVersion,proto3" json:"data_schema_version,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDetail) Reset()         { *m = ServiceDetail{} }
func (m *ServiceDetail) String() string { return proto.CompactTextString(m) }
func (*ServiceDetail) ProtoMessage()    {}
func (*ServiceDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{7}
}

func (m *ServiceDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDetail.Unmarshal(m, b)
}
func (m *ServiceDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDetail.Marshal(b, m, deterministic)
}
func (m *ServiceDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDetail.Merge(m, src)
}
func (m *ServiceDetail) XXX_Size() int {
	return xxx_messageInfo_ServiceDetail.Size(m)
}
func (m *ServiceDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDetail proto.InternalMessageInfo

func (m *ServiceDetail) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ServiceDetail) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceDetail) GetDataSchema() string {
	if m != nil {
		return m.DataSchema
	}
	return ""
}

func (m *ServiceDetail) GetDataSchemaVersion() string {
	if m != nil {
		return m.DataSchemaVersion
	}
	return ""
}

func (m *ServiceDetail) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ApproveService struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApproveService) Reset()         { *m = ApproveService{} }
func (m *ApproveService) String() string { return proto.CompactTextString(m) }
func (*ApproveService) ProtoMessage()    {}
func (*ApproveService) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{8}
}

func (m *ApproveService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApproveService.Unmarshal(m, b)
}
func (m *ApproveService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApproveService.Marshal(b, m, deterministic)
}
func (m *ApproveService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApproveService.Merge(m, src)
}
func (m *ApproveService) XXX_Size() int {
	return xxx_messageInfo_ApproveService.Size(m)
}
func (m *ApproveService) XXX_DiscardUnknown() {
	xxx_messageInfo_ApproveService.DiscardUnknown(m)
}

var xxx_messageInfo_ApproveService proto.InternalMessageInfo

func (m *ApproveService) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type TimeOutBlockRegisterIdentity struct {
	TimeOutBlock         int64    `protobuf:"varint,1,opt,name=time_out_block,json=timeOutBlock,proto3" json:"time_out_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeOutBlockRegisterIdentity) Reset()         { *m = TimeOutBlockRegisterIdentity{} }
func (m *TimeOutBlockRegisterIdentity) String() string { return proto.CompactTextString(m) }
func (*TimeOutBlockRegisterIdentity) ProtoMessage()    {}
func (*TimeOutBlockRegisterIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{9}
}

func (m *TimeOutBlockRegisterIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeOutBlockRegisterIdentity.Unmarshal(m, b)
}
func (m *TimeOutBlockRegisterIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeOutBlockRegisterIdentity.Marshal(b, m, deterministic)
}
func (m *TimeOutBlockRegisterIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeOutBlockRegisterIdentity.Merge(m, src)
}
func (m *TimeOutBlockRegisterIdentity) XXX_Size() int {
	return xxx_messageInfo_TimeOutBlockRegisterIdentity.Size(m)
}
func (m *TimeOutBlockRegisterIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeOutBlockRegisterIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_TimeOutBlockRegisterIdentity proto.InternalMessageInfo

func (m *TimeOutBlockRegisterIdentity) GetTimeOutBlock() int64 {
	if m != nil {
		return m.TimeOutBlock
	}
	return 0
}

type Proxy struct {
	ProxyNodeId          string   `protobuf:"bytes,1,opt,name=proxy_node_id,json=proxyNodeId,proto3" json:"proxy_node_id,omitempty"`
	Config               string   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proxy) Reset()         { *m = Proxy{} }
func (m *Proxy) String() string { return proto.CompactTextString(m) }
func (*Proxy) ProtoMessage()    {}
func (*Proxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{10}
}

func (m *Proxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proxy.Unmarshal(m, b)
}
func (m *Proxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proxy.Marshal(b, m, deterministic)
}
func (m *Proxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proxy.Merge(m, src)
}
func (m *Proxy) XXX_Size() int {
	return xxx_messageInfo_Proxy.Size(m)
}
func (m *Proxy) XXX_DiscardUnknown() {
	xxx_messageInfo_Proxy.DiscardUnknown(m)
}

var xxx_messageInfo_Proxy proto.InternalMessageInfo

func (m *Proxy) GetProxyNodeId() string {
	if m != nil {
		return m.ProxyNodeId
	}
	return ""
}

func (m *Proxy) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type BehindNodeList struct {
	Nodes                []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BehindNodeList) Reset()         { *m = BehindNodeList{} }
func (m *BehindNodeList) String() string { return proto.CompactTextString(m) }
func (*BehindNodeList) ProtoMessage()    {}
func (*BehindNodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{11}
}

func (m *BehindNodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BehindNodeList.Unmarshal(m, b)
}
func (m *BehindNodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BehindNodeList.Marshal(b, m, deterministic)
}
func (m *BehindNodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BehindNodeList.Merge(m, src)
}
func (m *BehindNodeList) XXX_Size() int {
	return xxx_messageInfo_BehindNodeList.Size(m)
}
func (m *BehindNodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_BehindNodeList.DiscardUnknown(m)
}

var xxx_messageInfo_BehindNodeList proto.InternalMessageInfo

func (m *BehindNodeList) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Request struct {
	RequestId            string         `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MinIdp               int64          `protobuf:"varint,2,opt,name=min_idp,json=minIdp,proto3" json:"min_idp,omitempty"`
	MinAal               float64        `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	MinIal               float64        `protobuf:"fixed64,4,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	RequestTimeout       int64          `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	IdpIdList            []string       `protobuf:"bytes,6,rep,name=idp_id_list,json=idpIdList,proto3" json:"idp_id_list,omitempty"`
	DataRequestList      []*DataRequest `protobuf:"bytes,7,rep,name=data_request_list,json=dataRequestList,proto3" json:"data_request_list,omitempty"`
	RequestMessageHash   string         `protobuf:"bytes,8,opt,name=request_message_hash,json=requestMessageHash,proto3" json:"request_message_hash,omitempty"`
	ResponseList         []*Response    `protobuf:"bytes,9,rep,name=response_list,json=responseList,proto3" json:"response_list,omitempty"`
	Closed               bool           `protobuf:"varint,10,opt,name=closed,proto3" json:"closed,omitempty"`
	TimedOut             bool           `protobuf:"varint,11,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Purpose              string         `protobuf:"bytes,12,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Owner                string         `protobuf:"bytes,13,opt,name=owner,proto3" json:"owner,omitempty"`
	Mode                 int32          `protobuf:"varint,14,opt,name=mode,proto3" json:"mode,omitempty"`
	UseCount             int64          `protobuf:"varint,15,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	CreationBlockHeight  int64          `protobuf:"varint,16,opt,name=creation_block_height,json=creationBlockHeight,proto3" json:"creation_block_height,omitempty"`
	ChainId              string         `protobuf:"bytes,17,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{12}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Request) GetMinIdp() int64 {
	if m != nil {
		return m.MinIdp
	}
	return 0
}

func (m *Request) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *Request) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *Request) GetRequestTimeout() int64 {
	if m != nil {
		return m.RequestTimeout
	}
	return 0
}

func (m *Request) GetIdpIdList() []string {
	if m != nil {
		return m.IdpIdList
	}
	return nil
}

func (m *Request) GetDataRequestList() []*DataRequest {
	if m != nil {
		return m.DataRequestList
	}
	return nil
}

func (m *Request) GetRequestMessageHash() string {
	if m != nil {
		return m.RequestMessageHash
	}
	return ""
}

func (m *Request) GetResponseList() []*Response {
	if m != nil {
		return m.ResponseList
	}
	return nil
}

func (m *Request) GetClosed() bool {
	if m != nil {
		return m.Closed
	}
	return false
}

func (m *Request) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *Request) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Request) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Request) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Request) GetUseCount() int64 {
	if m != nil {
		return m.UseCount
	}
	return 0
}

func (m *Request) GetCreationBlockHeight() int64 {
	if m != nil {
		return m.CreationBlockHeight
	}
	return 0
}

func (m *Request) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type DataRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AsIdList             []string `protobuf:"bytes,2,rep,name=as_id_list,json=asIdList,proto3" json:"as_id_list,omitempty"`
	MinAs                int64    `protobuf:"varint,3,opt,name=min_as,json=minAs,proto3" json:"min_as,omitempty"`
	RequestParamsHash    string   `protobuf:"bytes,4,opt,name=request_params_hash,json=requestParamsHash,proto3" json:"request_params_hash,omitempty"`
	AnsweredAsIdList     []string `protobuf:"bytes,5,rep,name=answered_as_id_list,json=answeredAsIdList,proto3" json:"answered_as_id_list,omitempty"`
	ReceivedDataFromList []string `protobuf:"bytes,6,rep,name=received_data_from_list,json=receivedDataFromList,proto3" json:"received_data_from_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{13}
}

func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (m *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(m, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *DataRequest) GetAsIdList() []string {
	if m != nil {
		return m.AsIdList
	}
	return nil
}

func (m *DataRequest) GetMinAs() int64 {
	if m != nil {
		return m.MinAs
	}
	return 0
}

func (m *DataRequest) GetRequestParamsHash() string {
	if m != nil {
		return m.RequestParamsHash
	}
	return ""
}

func (m *DataRequest) GetAnsweredAsIdList() []string {
	if m != nil {
		return m.AnsweredAsIdList
	}
	return nil
}

func (m *DataRequest) GetReceivedDataFromList() []string {
	if m != nil {
		return m.ReceivedDataFromList
	}
	return nil
}

type Response struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	Aal                  float64  `protobuf:"fixed64,2,opt,name=aal,proto3" json:"aal,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	IdpId                string   `protobuf:"bytes,5,opt,name=idp_id,json=idpId,proto3" json:"idp_id,omitempty"`
	ValidIal             string   `protobuf:"bytes,6,opt,name=valid_ial,json=validIal,proto3" json:"valid_ial,omitempty"`
	ValidSignature       string   `protobuf:"bytes,7,opt,name=valid_signature,json=validSignature,proto3" json:"valid_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{14}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *Response) GetAal() float64 {
	if m != nil {
		return m.Aal
	}
	return 0
}

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Response) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Response) GetIdpId() string {
	if m != nil {
		return m.IdpId
	}
	return ""
}

func (m *Response) GetValidIal() string {
	if m != nil {
		return m.ValidIal
	}
	return ""
}

func (m *Response) GetValidSignature() string {
	if m != nil {
		return m.ValidSignature
	}
	return ""
}

type ReportList struct {
	Reports              []*Report `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReportList) Reset()         { *m = ReportList{} }
func (m *ReportList) String() string { return proto.CompactTextString(m) }
func (*ReportList) ProtoMessage()    {}
func (*ReportList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{15}
}

func (m *ReportList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportList.Unmarshal(m, b)
}
func (m *ReportList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportList.Marshal(b, m, deterministic)
}
func (m *ReportList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportList.Merge(m, src)
}
func (m *ReportList) XXX_Size() int {
	return xxx_messageInfo_ReportList.Size(m)
}
func (m *ReportList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportList.DiscardUnknown(m)
}

var xxx_messageInfo_ReportList proto.InternalMessageInfo

func (m *ReportList) GetReports() []*Report {
	if m != nil {
		return m.Reports
	}
	return nil
}

type Report struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{16}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Report) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Report) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Accessor struct {
	AccessorId           string   `protobuf:"bytes,1,opt,name=accessor_id,json=accessorId,proto3" json:"accessor_id,omitempty"`
	AccessorType         string   `protobuf:"bytes,2,opt,name=accessor_type,json=accessorType,proto3" json:"accessor_type,omitempty"`
	AccessorPublicKey    string   `protobuf:"bytes,3,opt,name=accessor_public_key,json=accessorPublicKey,proto3" json:"accessor_public_key,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accessor) Reset()         { *m = Accessor{} }
func (m *Accessor) String() string { return proto.CompactTextString(m) }
func (*Accessor) ProtoMessage()    {}
func (*Accessor) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{17}
}

func (m *Accessor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accessor.Unmarshal(m, b)
}
func (m *Accessor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accessor.Marshal(b, m, deterministic)
}
func (m *Accessor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accessor.Merge(m, src)
}
func (m *Accessor) XXX_Size() int {
	return xxx_messageInfo_Accessor.Size(m)
}
func (m *Accessor) XXX_DiscardUnknown() {
	xxx_messageInfo_Accessor.DiscardUnknown(m)
}

var xxx_messageInfo_Accessor proto.InternalMessageInfo

func (m *Accessor) GetAccessorId() string {
	if m != nil {
		return m.AccessorId
	}
	return ""
}

func (m *Accessor) GetAccessorType() string {
	if m != nil {
		return m.AccessorType
	}
	return ""
}

func (m *Accessor) GetAccessorPublicKey() string {
	if m != nil {
		return m.AccessorPublicKey
	}
	return ""
}

func (m *Accessor) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Accessor) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type MsqDesList struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsqDesList) Reset()         { *m = MsqDesList{} }
func (m *MsqDesList) String() string { return proto.CompactTextString(m) }
func (*MsqDesList) ProtoMessage()    {}
func (*MsqDesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{18}
}

func (m *MsqDesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsqDesList.Unmarshal(m, b)
}
func (m *MsqDesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsqDesList.Marshal(b, m, deterministic)
}
func (m *MsqDesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsqDesList.Merge(m, src)
}
func (m *MsqDesList) XXX_Size() int {
	return xxx_messageInfo_MsqDesList.Size(m)
}
func (m *MsqDesList) XXX_DiscardUnknown() {
	xxx_messageInfo_MsqDesList.DiscardUnknown(m)
}

var xxx_messageInfo_MsqDesList proto.InternalMessageInfo

func (m *MsqDesList) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Ial                  float64  `protobuf:"fixed64,1,opt,name=ial,proto3" json:"ial,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	First                bool     `protobuf:"varint,4,opt,name=first,proto3" json:"first,omitempty"`
	TimeoutBlock         int64    `protobuf:"varint,5,opt,name=timeout_block,json=timeoutBlock,proto3" json:"timeout_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{19}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *Node) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Node) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Node) GetFirst() bool {
	if m != nil {
		return m.First
	}
	return false
}

func (m *Node) GetTimeoutBlock() int64 {
	if m != nil {
		return m.TimeoutBlock
	}
	return 0
}

type ServiceList struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{20}
}

func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (m *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(m, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	ServiceId              string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MinIal                 float64  `protobuf:"fixed64,2,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	MinAal                 float64  `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	Active                 bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Suspended              bool     `protobuf:"varint,5,opt,name=suspended,proto3" json:"suspended,omitempty"`
	SupportedNamespaceList []string `protobuf:"bytes,6,rep,name=supported_namespace_list,json=supportedNamespaceList,proto3" json:"supported_namespace_list,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{21}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Service) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *Service) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *Service) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Service) GetSuspended() bool {
	if m != nil {
		return m.Suspended
	}
	return false
}

func (m *Service) GetSupportedNamespaceList() []string {
	if m != nil {
		return m.SupportedNamespaceList
	}
	return nil
}

type ServiceDesList struct {
	Node                 []*ASNode `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServiceDesList) Reset()         { *m = ServiceDesList{} }
func (m *ServiceDesList) String() string { return proto.CompactTextString(m) }
func (*ServiceDesList) ProtoMessage()    {}
func (*ServiceDesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{22}
}

func (m *ServiceDesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDesList.Unmarshal(m, b)
}
func (m *ServiceDesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDesList.Marshal(b, m, deterministic)
}
func (m *ServiceDesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDesList.Merge(m, src)
}
func (m *ServiceDesList) XXX_Size() int {
	return xxx_messageInfo_ServiceDesList.Size(m)
}
func (m *ServiceDesList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDesList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDesList proto.InternalMessageInfo

func (m *ServiceDesList) GetNode() []*ASNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type ASNode struct {
	NodeId                 string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MinIal                 float64  `protobuf:"fixed64,2,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	MinAal                 float64  `protobuf:"fixed64,3,opt,name=min_aal,json=minAal,proto3" json:"min_aal,omitempty"`
	ServiceId              string   `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	SupportedNamespaceList []string `protobuf:"bytes,5,rep,name=supported_namespace_list,json=supportedNamespaceList,proto3" json:"supported_namespace_list,omitempty"`
	Active                 bool     `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ASNode) Reset()         { *m = ASNode{} }
func (m *ASNode) String() string { return proto.CompactTextString(m) }
func (*ASNode) ProtoMessage()    {}
func (*ASNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{23}
}

func (m *ASNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASNode.Unmarshal(m, b)
}
func (m *ASNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASNode.Marshal(b, m, deterministic)
}
func (m *ASNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASNode.Merge(m, src)
}
func (m *ASNode) XXX_Size() int {
	return xxx_messageInfo_ASNode.Size(m)
}
func (m *ASNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ASNode.DiscardUnknown(m)
}

var xxx_messageInfo_ASNode proto.InternalMessageInfo

func (m *ASNode) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ASNode) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

func (m *ASNode) GetMinAal() float64 {
	if m != nil {
		return m.MinAal
	}
	return 0
}

func (m *ASNode) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ASNode) GetSupportedNamespaceList() []string {
	if m != nil {
		return m.SupportedNamespaceList
	}
	return nil
}

func (m *ASNode) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type RPList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPList) Reset()         { *m = RPList{} }
func (m *RPList) String() string { return proto.CompactTextString(m) }
func (*RPList) ProtoMessage()    {}
func (*RPList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{24}
}

func (m *RPList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPList.Unmarshal(m, b)
}
func (m *RPList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPList.Marshal(b, m, deterministic)
}
func (m *RPList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPList.Merge(m, src)
}
func (m *RPList) XXX_Size() int {
	return xxx_messageInfo_RPList.Size(m)
}
func (m *RPList) XXX_DiscardUnknown() {
	xxx_messageInfo_RPList.DiscardUnknown(m)
}

var xxx_messageInfo_RPList proto.InternalMessageInfo

func (m *RPList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type ASList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ASList) Reset()         { *m = ASList{} }
func (m *ASList) String() string { return proto.CompactTextString(m) }
func (*ASList) ProtoMessage()    {}
func (*ASList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{25}
}

func (m *ASList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ASList.Unmarshal(m, b)
}
func (m *ASList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ASList.Marshal(b, m, deterministic)
}
func (m *ASList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ASList.Merge(m, src)
}
func (m *ASList) XXX_Size() int {
	return xxx_messageInfo_ASList.Size(m)
}
func (m *ASList) XXX_DiscardUnknown() {
	xxx_messageInfo_ASList.DiscardUnknown(m)
}

var xxx_messageInfo_ASList proto.InternalMessageInfo

func (m *ASList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type AllList struct {
	NodeId               []string `protobuf:"bytes,1,rep,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllList) Reset()         { *m = AllList{} }
func (m *AllList) String() string { return proto.CompactTextString(m) }
func (*AllList) ProtoMessage()    {}
func (*AllList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{26}
}

func (m *AllList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllList.Unmarshal(m, b)
}
func (m *AllList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllList.Marshal(b, m, deterministic)
}
func (m *AllList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllList.Merge(m, src)
}
func (m *AllList) XXX_Size() int {
	return xxx_messageInfo_AllList.Size(m)
}
func (m *AllList) XXX_DiscardUnknown() {
	xxx_messageInfo_AllList.DiscardUnknown(m)
}

var xxx_messageInfo_AllList proto.InternalMessageInfo

func (m *AllList) GetNodeId() []string {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type AccessorInGroup struct {
	Accessors            []string `protobuf:"bytes,1,rep,name=accessors,proto3" json:"accessors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessorInGroup) Reset()         { *m = AccessorInGroup{} }
func (m *AccessorInGroup) String() string { return proto.CompactTextString(m) }
func (*AccessorInGroup) ProtoMessage()    {}
func (*AccessorInGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{27}
}

func (m *AccessorInGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessorInGroup.Unmarshal(m, b)
}
func (m *AccessorInGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessorInGroup.Marshal(b, m, deterministic)
}
func (m *AccessorInGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessorInGroup.Merge(m, src)
}
func (m *AccessorInGroup) XXX_Size() int {
	return xxx_messageInfo_AccessorInGroup.Size(m)
}
func (m *AccessorInGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessorInGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AccessorInGroup proto.InternalMessageInfo

func (m *AccessorInGroup) GetAccessors() []string {
	if m != nil {
		return m.Accessors
	}
	return nil
}

type Token struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{28}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TokenPrice struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenPrice) Reset()         { *m = TokenPrice{} }
func (m *TokenPrice) String() string { return proto.CompactTextString(m) }
func (*TokenPrice) ProtoMessage()    {}
func (*TokenPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{29}
}

func (m *TokenPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenPrice.Unmarshal(m, b)
}
func (m *TokenPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenPrice.Marshal(b, m, deterministic)
}
func (m *TokenPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenPrice.Merge(m, src)
}
func (m *TokenPrice) XXX_Size() int {
	return xxx_messageInfo_TokenPrice.Size(m)
}
func (m *TokenPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenPrice.DiscardUnknown(m)
}

var xxx_messageInfo_TokenPrice proto.InternalMessageInfo

func (m *TokenPrice) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ReferenceGroup struct {
	Identities           []*IdentityInRefGroup `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	Idps                 []*IdPInRefGroup      `protobuf:"bytes,2,rep,name=idps,proto3" json:"idps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReferenceGroup) Reset()         { *m = ReferenceGroup{} }
func (m *ReferenceGroup) String() string { return proto.CompactTextString(m) }
func (*ReferenceGroup) ProtoMessage()    {}
func (*ReferenceGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{30}
}

func (m *ReferenceGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceGroup.Unmarshal(m, b)
}
func (m *ReferenceGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceGroup.Marshal(b, m, deterministic)
}
func (m *ReferenceGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceGroup.Merge(m, src)
}
func (m *ReferenceGroup) XXX_Size() int {
	return xxx_messageInfo_ReferenceGroup.Size(m)
}
func (m *ReferenceGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceGroup proto.InternalMessageInfo

func (m *ReferenceGroup) GetIdentities() []*IdentityInRefGroup {
	if m != nil {
		return m.Identities
	}
	return nil
}

func (m *ReferenceGroup) GetIdps() []*IdPInRefGroup {
	if m != nil {
		return m.Idps
	}
	return nil
}

type IdPInRefGroup struct {
	NodeId               string      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Mode                 []int32     `protobuf:"varint,2,rep,packed,name=mode,proto3" json:"mode,omitempty"`
	Accessors            []*Accessor `protobuf:"bytes,3,rep,name=accessors,proto3" json:"accessors,omitempty"`
	Ial                  float64     `protobuf:"fixed64,4,opt,name=ial,proto3" json:"ial,omitempty"`
	Active               bool        `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IdPInRefGroup) Reset()         { *m = IdPInRefGroup{} }
func (m *IdPInRefGroup) String() string { return proto.CompactTextString(m) }
func (*IdPInRefGroup) ProtoMessage()    {}
func (*IdPInRefGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{31}
}

func (m *IdPInRefGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdPInRefGroup.Unmarshal(m, b)
}
func (m *IdPInRefGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdPInRefGroup.Marshal(b, m, deterministic)
}
func (m *IdPInRefGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdPInRefGroup.Merge(m, src)
}
func (m *IdPInRefGroup) XXX_Size() int {
	return xxx_messageInfo_IdPInRefGroup.Size(m)
}
func (m *IdPInRefGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_IdPInRefGroup.DiscardUnknown(m)
}

var xxx_messageInfo_IdPInRefGroup proto.InternalMessageInfo

func (m *IdPInRefGroup) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *IdPInRefGroup) GetMode() []int32 {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (m *IdPInRefGroup) GetAccessors() []*Accessor {
	if m != nil {
		return m.Accessors
	}
	return nil
}

func (m *IdPInRefGroup) GetIal() float64 {
	if m != nil {
		return m.Ial
	}
	return 0
}

func (m *IdPInRefGroup) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type IdentityInRefGroup struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	IdentifierHash       string   `protobuf:"bytes,2,opt,name=identifier_hash,json=identifierHash,proto3" json:"identifier_hash,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityInRefGroup) Reset()         { *m = IdentityInRefGroup{} }
func (m *IdentityInRefGroup) String() string { return proto.CompactTextString(m) }
func (*IdentityInRefGroup) ProtoMessage()    {}
func (*IdentityInRefGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{32}
}

func (m *IdentityInRefGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityInRefGroup.Unmarshal(m, b)
}
func (m *IdentityInRefGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityInRefGroup.Marshal(b, m, deterministic)
}
func (m *IdentityInRefGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityInRefGroup.Merge(m, src)
}
func (m *IdentityInRefGroup) XXX_Size() int {
	return xxx_messageInfo_IdentityInRefGroup.Size(m)
}
func (m *IdentityInRefGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityInRefGroup.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityInRefGroup proto.InternalMessageInfo

func (m *IdentityInRefGroup) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *IdentityInRefGroup) GetIdentifierHash() string {
	if m != nil {
		return m.IdentifierHash
	}
	return ""
}

func (m *IdentityInRefGroup) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type AllowedModeList struct {
	Mode                 []int32  `protobuf:"varint,1,rep,packed,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowedModeList) Reset()         { *m = AllowedModeList{} }
func (m *AllowedModeList) String() string { return proto.CompactTextString(m) }
func (*AllowedModeList) ProtoMessage()    {}
func (*AllowedModeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{33}
}

func (m *AllowedModeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowedModeList.Unmarshal(m, b)
}
func (m *AllowedModeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowedModeList.Marshal(b, m, deterministic)
}
func (m *AllowedModeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowedModeList.Merge(m, src)
}
func (m *AllowedModeList) XXX_Size() int {
	return xxx_messageInfo_AllowedModeList.Size(m)
}
func (m *AllowedModeList) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowedModeList.DiscardUnknown(m)
}

var xxx_messageInfo_AllowedModeList proto.InternalMessageInfo

func (m *AllowedModeList) GetMode() []int32 {
	if m != nil {
		return m.Mode
	}
	return nil
}

type AllowedMinIalForRegisterIdentityAtFirstIdp struct {
	MinIal               float64  `protobuf:"fixed64,1,opt,name=min_ial,json=minIal,proto3" json:"min_ial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllowedMinIalForRegisterIdentityAtFirstIdp) Reset() {
	*m = AllowedMinIalForRegisterIdentityAtFirstIdp{}
}
func (m *AllowedMinIalForRegisterIdentityAtFirstIdp) String() string {
	return proto.CompactTextString(m)
}
func (*AllowedMinIalForRegisterIdentityAtFirstIdp) ProtoMessage() {}
func (*AllowedMinIalForRegisterIdentityAtFirstIdp) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{34}
}

func (m *AllowedMinIalForRegisterIdentityAtFirstIdp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllowedMinIalForRegisterIdentityAtFirstIdp.Unmarshal(m, b)
}
func (m *AllowedMinIalForRegisterIdentityAtFirstIdp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllowedMinIalForRegisterIdentityAtFirstIdp.Marshal(b, m, deterministic)
}
func (m *AllowedMinIalForRegisterIdentityAtFirstIdp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowedMinIalForRegisterIdentityAtFirstIdp.Merge(m, src)
}
func (m *AllowedMinIalForRegisterIdentityAtFirstIdp) XXX_Size() int {
	return xxx_messageInfo_AllowedMinIalForRegisterIdentityAtFirstIdp.Size(m)
}
func (m *AllowedMinIalForRegisterIdentityAtFirstIdp) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowedMinIalForRegisterIdentityAtFirstIdp.DiscardUnknown(m)
}

var xxx_messageInfo_AllowedMinIalForRegisterIdentityAtFirstIdp proto.InternalMessageInfo

func (m *AllowedMinIalForRegisterIdentityAtFirstIdp) GetMinIal() float64 {
	if m != nil {
		return m.MinIal
	}
	return 0
}

type ErrorCode struct {
	ErrorCode            string   `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fatal                bool     `protobuf:"varint,3,opt,name=fatal,proto3" json:"fatal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorCode) Reset()         { *m = ErrorCode{} }
func (m *ErrorCode) String() string { return proto.CompactTextString(m) }
func (*ErrorCode) ProtoMessage()    {}
func (*ErrorCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{35}
}

func (m *ErrorCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorCode.Unmarshal(m, b)
}
func (m *ErrorCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorCode.Marshal(b, m, deterministic)
}
func (m *ErrorCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorCode.Merge(m, src)
}
func (m *ErrorCode) XXX_Size() int {
	return xxx_messageInfo_ErrorCode.Size(m)
}
func (m *ErrorCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorCode.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorCode proto.InternalMessageInfo

func (m *ErrorCode) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *ErrorCode) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorCode) GetFatal() bool {
	if m != nil {
		return m.Fatal
	}
	return false
}

type ErrorCodeList struct {
	ErrorCode            []*ErrorCode `protobuf:"bytes,2,rep,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ErrorCodeList) Reset()         { *m = ErrorCodeList{} }
func (m *ErrorCodeList) String() string { return proto.CompactTextString(m) }
func (*ErrorCodeList) ProtoMessage()    {}
func (*ErrorCodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_492be2f0ffbab25c, []int{36}
}

func (m *ErrorCodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorCodeList.Unmarshal(m, b)
}
func (m *ErrorCodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorCodeList.Marshal(b, m, deterministic)
}
func (m *ErrorCodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorCodeList.Merge(m, src)
}
func (m *ErrorCodeList) XXX_Size() int {
	return xxx_messageInfo_ErrorCodeList.Size(m)
}
func (m *ErrorCodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorCodeList.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorCodeList proto.InternalMessageInfo

func (m *ErrorCodeList) GetErrorCode() []*ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyVersions)(nil), "KeyVersions")
	proto.RegisterType((*NodeDetail)(nil), "NodeDetail")
	proto.RegisterType((*MQ)(nil), "MQ")
	proto.RegisterType((*IdPList)(nil), "IdPList")
	proto.RegisterType((*NamespaceList)(nil), "NamespaceList")
	proto.RegisterType((*Namespace)(nil), "Namespace")
	proto.RegisterType((*ServiceDetailList)(nil), "ServiceDetailList")
	proto.RegisterType((*ServiceDetail)(nil), "ServiceDetail")
	proto.RegisterType((*ApproveService)(nil), "ApproveService")
	proto.RegisterType((*TimeOutBlockRegisterIdentity)(nil), "TimeOutBlockRegisterIdentity")
	proto.RegisterType((*Proxy)(nil), "Proxy")
	proto.RegisterType((*BehindNodeList)(nil), "BehindNodeList")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ReportList)(nil), "ReportList")
	proto.RegisterType((*Report)(nil), "Report")
	proto.RegisterType((*Accessor)(nil), "Accessor")
	proto.RegisterType((*MsqDesList)(nil), "MsqDesList")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*ServiceList)(nil), "ServiceList")
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*ServiceDesList)(nil), "ServiceDesList")
	proto.RegisterType((*ASNode)(nil), "ASNode")
	proto.RegisterType((*RPList)(nil), "RPList")
	proto.RegisterType((*ASList)(nil), "ASList")
	proto.RegisterType((*AllList)(nil), "AllList")
	proto.RegisterType((*AccessorInGroup)(nil), "AccessorInGroup")
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*TokenPrice)(nil), "TokenPrice")
	proto.RegisterType((*ReferenceGroup)(nil), "ReferenceGroup")
	proto.RegisterType((*IdPInRefGroup)(nil), "IdPInRefGroup")
	proto.RegisterType((*IdentityInRefGroup)(nil), "IdentityInRefGroup")
	proto.RegisterType((*AllowedModeList)(nil), "AllowedModeList")
	proto.RegisterType((*AllowedMinIalForRegisterIdentityAtFirstIdp)(nil), "AllowedMinIalForRegisterIdentityAtFirstIdp")
	proto.RegisterType((*ErrorCode)(nil), "ErrorCode")
	proto.RegisterType((*ErrorCodeList)(nil), "ErrorCodeList")
}

func init() { proto.RegisterFile("protos/data/data.proto", fileDescriptor_492be2f0ffbab25c) }

var fileDescriptor_492be2f0ffbab25c = []byte{
	// 1727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xcd, 0x6e, 0x1c, 0xc7,
	0x11, 0xc6, 0xec, 0xff, 0xd6, 0x92, 0x4b, 0x71, 0x28, 0xcb, 0x93, 0x58, 0x8e, 0xa9, 0x8e, 0x23,
	0xad, 0x14, 0x7b, 0x15, 0x50, 0x08, 0x60, 0x24, 0x87, 0x60, 0x2d, 0x59, 0xf1, 0xc6, 0xa1, 0x4d,
	0x8f, 0x94, 0x1c, 0x92, 0x00, 0x83, 0xd6, 0x4c, 0x93, 0xdb, 0xd0, 0xfc, 0xa9, 0x7b, 0x86, 0x12,
	0xef, 0x39, 0x06, 0xc8, 0x7b, 0xe4, 0x90, 0x07, 0x08, 0x90, 0x43, 0x80, 0x9c, 0xf2, 0x42, 0xb9,
	0x06, 0x55, 0xdd, 0x3d, 0x33, 0x2b, 0x99, 0x64, 0x7c, 0x21, 0xa6, 0xbe, 0xaa, 0x9e, 0x9e, 0xfa,
	0xfb, 0xaa, 0x96, 0x70, 0xab, 0x54, 0x45, 0x55, 0xe8, 0x87, 0x09, 0xaf, 0x38, 0xfd, 0x59, 0x12,
	0xc0, 0xee, 0xc3, 0xec, 0x2b, 0x71, 0xf1, 0x7b, 0xa1, 0xb4, 0x2c, 0x72, 0xed, 0xff, 0x10, 0x26,
	0xe7, 0xf6, 0x39, 0xf0, 0x0e, 0xfb, 0x8b, 0x7e, 0xd8, 0xc8, 0xec, 0x2f, 0x7d, 0x80, 0xaf, 0x8b,
	0x44, 0x3c, 0x11, 0x15, 0x97, 0xa9, 0xff, 0x21, 0x40, 0x59, 0xbf, 0x48, 0x65, 0x1c, 0xbd, 0x14,
	0x17, 0x81, 0x77, 0xe8, 0x2d, 0xa6, 0xe1, 0xd4, 0x20, 0x5f, 0x89, 0x0b, 0xff, 0x01, 0xec, 0x67,
	0x5c, 0x57, 0x42, 0x45, 0x1d, 0xab, 0x1e, 0x59, 0xed, 0x19, 0xc5, 0x49, 0x63, 0xfb, 0x01, 0x4c,
	0xf3, 0x22, 0x11, 0x51, 0xce, 0x33, 0x11, 0xf4, 0xc9, 0x66, 0x82, 0xc0, 0xd7, 0x3c, 0x13, 0xbe,
	0x0f, 0x03, 0x55, 0xa4, 0x22, 0x18, 0x10, 0x4e, 0xcf, 0xfe, 0xfb, 0x30, 0xce, 0xf8, 0x9b, 0x48,
	0xf2, 0x34, 0x18, 0x1e, 0x7a, 0x0b, 0x2f, 0x1c, 0x65, 0xfc, 0xcd, 0x9a, 0xa7, 0x4e, 0xc1, 0x79,
	0x1a, 0x8c, 0x1a, 0xc5, 0x8a, 0xa7, 0xfe, 0x01, 0xf4, 0xb2, 0x57, 0xc1, 0xf8, 0xb0, 0xbf, 0x98,
	0x1d, 0xf5, 0x97, 0xc7, 0xdf, 0x86, 0xbd, 0xec, 0x95, 0x7f, 0x0b, 0x46, 0x3c, 0xae, 0xe4, 0xb9,
	0x08, 0x26, 0x87, 0xde, 0x62, 0x12, 0x5a, 0xc9, 0x67, 0xb0, 0x5b, 0xaa, 0xe2, 0xcd, 0x45, 0x44,
	0x5f, 0x25, 0x93, 0x60, 0x4a, 0x77, 0xcf, 0x08, 0xc4, 0x10, 0xac, 0x13, 0xff, 0x0e, 0xec, 0x18,
	0x9b, 0xb8, 0xc8, 0x4f, 0xe5, 0x59, 0x00, 0x1d, 0x93, 0xc7, 0x04, 0xf9, 0x7f, 0x82, 0x4f, 0x74,
	0x5d, 0x96, 0x85, 0xaa, 0x44, 0x12, 0x29, 0xf1, 0xaa, 0x16, 0xba, 0x8a, 0x32, 0xa1, 0x35, 0x3f,
	0x13, 0x11, 0xe6, 0x20, 0xaa, 0x55, 0x1a, 0x55, 0x17, 0xa5, 0x88, 0x52, 0xa9, 0xab, 0x60, 0x76,
	0xd8, 0x5f, 0x4c, 0xc3, 0xbb, 0xcd, 0x99, 0xd0, 0x1c, 0x39, 0x36, 0x27, 0x9e, 0xf0, 0x8a, 0xff,
	0x4e, 0xa5, 0xcf, 0x2f, 0x4a, 0xf1, 0x5b, 0xa9, 0x2b, 0xb6, 0x80, 0xde, 0xf1, 0xb7, 0xfe, 0x1c,
	0x7a, 0xb2, 0xb4, 0xd1, 0xef, 0xc9, 0x12, 0xa3, 0x85, 0x87, 0x29, 0xd2, 0xfd, 0x90, 0x9e, 0x19,
	0x83, 0xf1, 0x3a, 0x39, 0xc1, 0x43, 0x18, 0x1f, 0xe7, 0x93, 0x47, 0xb7, 0x8d, 0x72, 0x72, 0x87,
	0xfd, 0x12, 0x76, 0x31, 0xda, 0xba, 0xe4, 0x31, 0xbd, 0xde, 0x7f, 0x00, 0x90, 0x3b, 0xc0, 0xd4,
	0xc2, 0xec, 0x08, 0x96, 0x8d, 0x4d, 0xd8, 0xd1, 0xb2, 0xbf, 0xf5, 0x60, 0xda, 0x68, 0xfc, 0xdb,
	0x30, 0x6d, 0x74, 0xae, 0x2e, 0x1a, 0xc0, 0x3f, 0x84, 0x59, 0x22, 0x74, 0xac, 0x64, 0x59, 0xc9,
	0x22, 0xb7, 0x15, 0xd1, 0x85, 0x3a, 0x59, 0xe9, 0x6f, 0x65, 0xe5, 0x8f, 0xf0, 0x53, 0x9e, 0xa6,
	0xc5, 0x6b, 0x91, 0x44, 0x32, 0x11, 0x79, 0x25, 0x4f, 0xa5, 0x50, 0x51, 0x5c, 0xd4, 0x79, 0x15,
	0xc9, 0x3c, 0x52, 0xe2, 0x54, 0x28, 0x91, 0xc7, 0x22, 0x3a, 0x53, 0x45, 0x5d, 0x52, 0xbd, 0x0c,
	0xc3, 0xbb, 0xf6, 0xc8, 0xba, 0x39, 0xf1, 0x18, 0x0f, 0xac, 0xf3, 0xd0, 0x99, 0xff, 0x1a, 0xad,
	0xfd, 0x0d, 0x1c, 0xb9, 0x97, 0x9b, 0xeb, 0xfe, 0xaf, 0x3b, 0x86, 0x74, 0xc7, 0x27, 0xf6, 0xe4,
	0x8a, 0x0e, 0x5e, 0x73, 0x13, 0xfb, 0x15, 0xec, 0x3f, 0x13, 0xea, 0x5c, 0xc6, 0xb6, 0x91, 0x6c,
	0xb4, 0x27, 0xda, 0x80, 0x2e, 0xd6, 0xf3, 0xe5, 0x96, 0x55, 0xd8, 0xe8, 0xd9, 0x3f, 0x3c, 0xd8,
	0xdd, 0xd2, 0x61, 0x2b, 0x5a, 0xad, 0x49, 0x2c, 0x85, 0xdc, 0x22, 0xa6, 0x54, 0x9d, 0x9a, 0x3a,
	0xcc, 0xc6, 0xdc, 0x62, 0xd4, 0x64, 0x1f, 0xc1, 0x8c, 0x0a, 0x52, 0xc7, 0x1b, 0x91, 0x71, 0xdb,
	0x83, 0x80, 0xd0, 0x33, 0x42, 0xfc, 0x25, 0x1c, 0x74, 0x0c, 0x22, 0x4b, 0x0a, 0xb6, 0x29, 0xf7,
	0x5b, 0x43, 0xcb, 0x24, 0x9d, 0x24, 0x0e, 0xbb, 0x49, 0x64, 0x0b, 0x98, 0xaf, 0xca, 0x52, 0x15,
	0xe7, 0xc2, 0xba, 0xd0, 0xb1, 0xf4, 0xb6, 0x2c, 0x9f, 0xc0, 0xed, 0xe7, 0x32, 0x13, 0xdf, 0xd4,
	0xd5, 0xe7, 0x69, 0x11, 0xbf, 0x0c, 0xc5, 0x99, 0x44, 0xd6, 0x30, 0xe1, 0xad, 0x2e, 0xfc, 0x8f,
	0x61, 0x5e, 0xc9, 0x4c, 0x44, 0x45, 0x5d, 0x45, 0x2f, 0xd0, 0x82, 0xce, 0xf7, 0xc3, 0x9d, 0xaa,
	0x73, 0x8a, 0x3d, 0x86, 0xe1, 0x09, 0xb6, 0xe4, 0xbb, 0x3d, 0xed, 0xbd, 0xdb, 0xd3, 0xb7, 0x60,
	0x64, 0xbb, 0xd9, 0x84, 0xc8, 0x4a, 0xec, 0x2e, 0xcc, 0x3f, 0x17, 0x1b, 0x99, 0x27, 0x68, 0x47,
	0xf9, 0xba, 0x09, 0x43, 0x7c, 0x8f, 0xb6, 0x5d, 0x64, 0x04, 0xf6, 0xcf, 0x01, 0x8c, 0x6d, 0xd3,
	0x62, 0x4e, 0x5c, 0xcb, 0xb7, 0x39, 0xb1, 0xc8, 0x3a, 0x21, 0xa2, 0x92, 0x79, 0x24, 0x93, 0xd2,
	0xb6, 0xea, 0x28, 0x93, 0xf9, 0x3a, 0x29, 0x9d, 0x02, 0x19, 0xac, 0x6f, 0x19, 0x4c, 0xe6, 0x2b,
	0x4b, 0x6d, 0x78, 0x82, 0xa7, 0x14, 0x75, 0xa3, 0x40, 0xce, 0xbb, 0x07, 0x7b, 0xee, 0x26, 0x74,
	0xbd, 0xa8, 0x2b, 0x8a, 0x79, 0x3f, 0x9c, 0x5b, 0xf8, 0xb9, 0x41, 0xfd, 0x1f, 0xc1, 0x4c, 0x26,
	0x65, 0x24, 0x13, 0x43, 0x37, 0x23, 0xfa, 0xf4, 0xa9, 0x4c, 0xca, 0x75, 0x42, 0x4e, 0x7d, 0x06,
	0x94, 0xc8, 0x86, 0xaa, 0xc8, 0xca, 0x50, 0xe6, 0xce, 0x12, 0xe9, 0xc7, 0xfa, 0x16, 0xee, 0x25,
	0xad, 0x40, 0x27, 0x7f, 0x06, 0x37, 0xdf, 0xe6, 0xb7, 0x0d, 0xd7, 0x1b, 0xa2, 0xd5, 0x69, 0xe8,
	0xab, 0x2d, 0x22, 0xfb, 0x92, 0xeb, 0x8d, 0xbf, 0x84, 0x5d, 0x25, 0x74, 0x59, 0xe4, 0xda, 0x92,
	0xdf, 0x94, 0xee, 0x99, 0x2e, 0x43, 0x8b, 0x86, 0x3b, 0x4e, 0x4f, 0x37, 0x60, 0x6a, 0xd2, 0x42,
	0x8b, 0x84, 0x88, 0x76, 0x12, 0x5a, 0x09, 0x47, 0x07, 0x3a, 0x9d, 0x60, 0x19, 0x04, 0x33, 0x52,
	0x4d, 0x08, 0xf8, 0xa6, 0xae, 0xfc, 0x00, 0xc6, 0x65, 0xad, 0xca, 0x42, 0x8b, 0x60, 0x87, 0xbe,
	0xc4, 0x89, 0x98, 0xbf, 0xe2, 0x75, 0x2e, 0x54, 0xb0, 0x4b, 0xb8, 0x11, 0x90, 0x3c, 0xb3, 0x22,
	0x11, 0xc1, 0x9c, 0xda, 0x9a, 0x9e, 0xf1, 0x82, 0x5a, 0x0b, 0x43, 0x01, 0xc1, 0x1e, 0xc5, 0x75,
	0x52, 0x6b, 0x41, 0xbd, 0xed, 0x1f, 0xc1, 0x7b, 0xb1, 0x12, 0x1c, 0x69, 0xcb, 0xd4, 0x60, 0xb4,
	0x11, 0xf2, 0x6c, 0x53, 0x05, 0x37, 0xc8, 0xf0, 0xc0, 0x29, 0xa9, 0x16, 0xbf, 0x24, 0x95, 0xff,
	0x03, 0x98, 0xc4, 0x1b, 0x4e, 0xb9, 0x0f, 0xf6, 0xcd, 0x57, 0x91, 0xbc, 0x4e, 0xd8, 0x7f, 0x3d,
	0x98, 0x75, 0xe2, 0x7c, 0x5d, 0x5f, 0xdf, 0x06, 0xe0, 0xba, 0x49, 0x67, 0x8f, 0xd2, 0x39, 0xe1,
	0xda, 0x66, 0xf3, 0x3d, 0x18, 0x51, 0x21, 0x69, 0xaa, 0xa3, 0x7e, 0x38, 0xc4, 0x3a, 0xd2, 0xd8,
	0xc8, 0x2e, 0x55, 0x25, 0x57, 0x3c, 0xd3, 0x26, 0x53, 0xb6, 0x91, 0xad, 0xea, 0x84, 0x34, 0x94,
	0xa8, 0x4f, 0xe1, 0x80, 0xe7, 0xfa, 0xb5, 0x50, 0xc8, 0x8c, 0xed, 0x6d, 0x43, 0xba, 0xed, 0x86,
	0x53, 0xad, 0xdc, 0xad, 0x3f, 0x87, 0xf7, 0x95, 0x88, 0x85, 0x3c, 0x17, 0x89, 0x19, 0x71, 0xa7,
	0xaa, 0xc8, 0xba, 0xf5, 0x76, 0xd3, 0xa9, 0xd1, 0xd1, 0xa7, 0xaa, 0xc8, 0x68, 0x98, 0xfd, 0xcb,
	0x83, 0x89, 0xcb, 0xbc, 0x7f, 0x03, 0xfa, 0x58, 0xe5, 0x1e, 0x55, 0x39, 0x3e, 0x22, 0x82, 0x0d,
	0xd1, 0x33, 0x08, 0xe7, 0x29, 0xd6, 0x83, 0xae, 0x78, 0x55, 0x6b, 0xcb, 0x55, 0x56, 0xc2, 0xe1,
	0xa3, 0xe5, 0x59, 0xce, 0xab, 0x5a, 0xb9, 0x95, 0xa1, 0x05, 0x30, 0x26, 0xa6, 0x03, 0xa8, 0x43,
	0xa6, 0xe1, 0x90, 0x8a, 0x1f, 0x73, 0x7c, 0xce, 0x53, 0x99, 0x50, 0x73, 0x8d, 0xcc, 0xfe, 0x41,
	0x80, 0x6d, 0x2f, 0xa3, 0x6c, 0xdf, 0x3b, 0x26, 0x93, 0x39, 0xc1, 0xcf, 0x1c, 0xca, 0x1e, 0x02,
	0x84, 0x02, 0x07, 0x2e, 0x05, 0xe2, 0x0e, 0x8c, 0x15, 0x49, 0x8e, 0xd0, 0xc7, 0x4b, 0xa3, 0x0d,
	0x1d, 0xce, 0x7e, 0x03, 0x23, 0x03, 0xa1, 0x37, 0x99, 0xa8, 0x36, 0x85, 0x4b, 0xb2, 0x95, 0xb0,
	0x4c, 0x4b, 0x25, 0x63, 0x61, 0x3d, 0x37, 0x02, 0x96, 0x29, 0x86, 0xd6, 0x7a, 0x4e, 0xcf, 0xec,
	0xef, 0x1e, 0x4c, 0x56, 0x71, 0x2c, 0xb4, 0x2e, 0x14, 0xb2, 0x39, 0xb7, 0xcf, 0x6d, 0xe1, 0x80,
	0x83, 0xd6, 0x89, 0xff, 0x63, 0xd8, 0x6d, 0x0c, 0x70, 0xff, 0xb0, 0x7c, 0xb7, 0xe3, 0x40, 0x5c,
	0x32, 0xb0, 0x52, 0x1a, 0xa3, 0xce, 0x0e, 0x67, 0x6e, 0xdd, 0x77, 0xaa, 0x76, 0x8b, 0x6b, 0x89,
	0x7c, 0xb0, 0x35, 0xb7, 0x9b, 0x5e, 0x1b, 0x76, 0x7a, 0x8d, 0xdd, 0x07, 0x38, 0xd6, 0xaf, 0x9e,
	0x08, 0x4d, 0xd1, 0xfa, 0xa0, 0xcb, 0xa7, 0xb3, 0xa3, 0xe1, 0x12, 0x99, 0xd6, 0xd1, 0xea, 0x9f,
	0x3d, 0x18, 0xa0, 0xfc, 0x1d, 0x85, 0xd1, 0xd9, 0x67, 0x2c, 0x65, 0xe7, 0x0d, 0x95, 0x7f, 0xe7,
	0x12, 0x71, 0x13, 0x86, 0xa7, 0x52, 0xe9, 0xca, 0x7e, 0xa3, 0x11, 0x30, 0x1e, 0x96, 0x3a, 0xed,
	0x28, 0x19, 0xb6, 0xa3, 0xa4, 0x70, 0xa3, 0xe4, 0x11, 0xcc, 0xec, 0xcc, 0xa2, 0x4f, 0xfe, 0xf8,
	0x9d, 0x91, 0x3d, 0x71, 0x23, 0xbb, 0x33, 0xac, 0xff, 0xe3, 0xc1, 0xd8, 0x4d, 0xba, 0x6b, 0xda,
	0xb9, 0x43, 0xf0, 0xbd, 0x2d, 0x82, 0xbf, 0x74, 0x24, 0x5c, 0x16, 0x71, 0x6c, 0x82, 0x5a, 0x97,
	0x22, 0x4f, 0x44, 0x62, 0xe7, 0x6f, 0x0b, 0xf8, 0x9f, 0x41, 0xd0, 0xae, 0xa5, 0xcd, 0x62, 0xd6,
	0xed, 0xd1, 0x5b, 0x8d, 0x7e, 0x6b, 0x27, 0x64, 0x9f, 0xc2, 0xbc, 0x59, 0x3c, 0x5c, 0xde, 0x06,
	0x18, 0xf0, 0xa6, 0xc4, 0x57, 0xcf, 0x28, 0x71, 0x04, 0xb2, 0x7f, 0x7b, 0x30, 0x32, 0xc0, 0xf6,
	0xde, 0xd9, 0xcd, 0xd3, 0xf7, 0x77, 0x7a, 0x3b, 0x8a, 0x83, 0xb7, 0xa3, 0x78, 0x95, 0x77, 0xc3,
	0xab, 0xbc, 0xeb, 0x44, 0x73, 0xb4, 0xb5, 0x88, 0xdc, 0x81, 0x51, 0x78, 0xcd, 0xf6, 0x7c, 0x07,
	0x1d, 0xbd, 0xda, 0x84, 0xc1, 0x78, 0x95, 0xa6, 0x57, 0xdb, 0x3c, 0x84, 0x3d, 0xd7, 0xc3, 0xeb,
	0xdc, 0xec, 0xa5, 0xb7, 0x61, 0xea, 0x3a, 0xcd, 0x2d, 0x1b, 0x2d, 0xc0, 0x3e, 0x82, 0xe1, 0xf3,
	0xe2, 0xa5, 0x30, 0xeb, 0x56, 0x46, 0x23, 0xca, 0x34, 0x87, 0x95, 0x18, 0x03, 0x20, 0x83, 0x13,
	0x22, 0x8e, 0x86, 0x4e, 0xbc, 0x0e, 0x9d, 0x30, 0x09, 0xf3, 0xb7, 0x96, 0xe1, 0x47, 0x00, 0x66,
	0xfb, 0xad, 0x64, 0x53, 0xdc, 0x07, 0x4b, 0xb7, 0x79, 0xd1, 0x46, 0x4b, 0x86, 0x61, 0xc7, 0xcc,
	0x67, 0x30, 0x90, 0x49, 0xa9, 0x69, 0x0e, 0xe1, 0xfa, 0xba, 0x4e, 0x4e, 0x3a, 0x96, 0xa4, 0x63,
	0x7f, 0xf5, 0x60, 0x77, 0x0b, 0xbf, 0xbc, 0x30, 0xdc, 0x2c, 0xc6, 0xd7, 0xb9, 0x59, 0x7c, 0xaf,
	0x1b, 0x8c, 0xbe, 0x5d, 0x18, 0x5c, 0xc4, 0x3a, 0x71, 0x71, 0x44, 0x31, 0x68, 0x89, 0xe2, 0xb2,
	0x7d, 0x54, 0x83, 0xff, 0xae, 0x5f, 0xd7, 0xfc, 0x84, 0xb9, 0x07, 0x7b, 0x9d, 0x1f, 0x07, 0x34,
	0x3e, 0x0d, 0xf9, 0xcc, 0x5b, 0x98, 0x66, 0xe7, 0x25, 0x24, 0xc4, 0x7e, 0x02, 0x7b, 0x2b, 0xf3,
	0x93, 0xe1, 0xd8, 0x2d, 0x94, 0xce, 0x5d, 0xaf, 0x75, 0x97, 0x7d, 0x01, 0x0f, 0x9c, 0x19, 0xf5,
	0xc4, 0xd3, 0x42, 0xbd, 0xbd, 0x05, 0xaf, 0xaa, 0xa7, 0x48, 0x60, 0x9d, 0xc5, 0xb1, 0x25, 0x48,
	0xdb, 0x49, 0xec, 0x0f, 0x30, 0xfd, 0x42, 0xa9, 0x42, 0x3d, 0xc6, 0x10, 0x7e, 0x08, 0x20, 0x50,
	0x88, 0x62, 0x73, 0x1b, 0xb9, 0x26, 0x1a, 0x75, 0x00, 0x63, 0xbb, 0xc0, 0x59, 0x97, 0x9c, 0x48,
	0xc4, 0xc9, 0x2b, 0xdb, 0x8d, 0x48, 0x9c, 0x28, 0xb0, 0x5f, 0xc0, 0x6e, 0xf3, 0x6e, 0xf2, 0xe3,
	0xfe, 0xd6, 0xfb, 0x7b, 0xf6, 0x67, 0x63, 0x63, 0xd3, 0xb9, 0xeb, 0xc5, 0x88, 0xfe, 0x03, 0xf1,
	0xe8, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x21, 0x4d, 0x09, 0x5a, 0x9b, 0x10, 0x00, 0x00,
}
