FROM golang:1.10 as builder
LABEL maintainer="Narate Ketram <rate@dome.cloud>"

ENV CGO_ENABLED=0
RUN go get github.com/golang/dep/cmd/dep
COPY abci $GOPATH/src/github.com/ndidplatform/smart-contract/abci

WORKDIR $GOPATH/src/github.com/ndidplatform/smart-contract/abci
RUN dep ensure && go install


FROM alpine:3.7

ENV TERM=xterm-256color
COPY --from=builder /go/bin/abci /usr/bin/abci-server
ENTRYPOINT [ "abci-server" ]