FROM golang:1.10 as builder
LABEL maintainer="Narate Ketram <rate@dome.cloud>"

ENV CGO_ENABLED=0
RUN curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && \
    echo "31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315 /usr/local/bin/dep" | sha256sum -c && \
    chmod +x /usr/local/bin/dep

COPY abci/Gopkg.toml abci/Gopkg.lock $GOPATH/src/github.com/ndidplatform/smart-contract/abci/
WORKDIR $GOPATH/src/github.com/ndidplatform/smart-contract/abci
RUN dep ensure --vendor-only

COPY abci $GOPATH/src/github.com/ndidplatform/smart-contract/abci
RUN go install


FROM alpine:3.7

ENV TERM=xterm-256color
COPY --from=builder /go/bin/abci /usr/bin/abci-server
ENTRYPOINT [ "abci-server" ]