FROM alpine:3.6 as build

# This is the release of tendermint to pull in.
ENV TM_VERSION 0.22.0
ENV TM_SHA256SUM 7bf5e3faf06b7bb45caeb9c202f8b159f7cacc0ce38fb55318af4815126aa840

RUN apk update && apk add --no-cache --virtual .build-deps \
        openssl \
        && \
    wget -qO /tmp/tendermint.zip https://github.com/tendermint/tendermint/releases/download/v${TM_VERSION}/tendermint_${TM_VERSION}_linux_amd64.zip && \
    echo "${TM_SHA256SUM}  /tmp/tendermint.zip" | sha256sum -c && \
    unzip -d /usr/bin /tmp/tendermint.zip && \
    rm -f tendermint.zip && \
    apk del .build-deps


FROM alpine:3.7

# Tendermint will be looking for genesis file in /tendermint (unless you change
# `genesis_file` in config.toml). You can put your config.toml and private
# validator file into /tendermint.
#
# The /tendermint/data dir is used by tendermint to store state.
ENV TMHOME /tendermint

COPY --from=build /var/cache/apk /var/cache/apk

# jq and curl used for extracting `pub_key` from private validator while
# deploying tendermint with Kubernetes. It is nice to have bash so the users
# could execute bash commands.
RUN apk update && apk add --no-cache bash curl jq

COPY --from=build /usr/bin/tendermint /usr/bin/tendermint
COPY docker/start-node.sh /usr/bin/

ENTRYPOINT ["start-node.sh"]
STOPSIGNAL SIGTERM