FROM alpine:3.7 as build

# This is the release of tendermint to pull in.
ENV TM_DOWNLOAD_PATH 0.22.8
ENV TM_VERSION 0.22.8
ENV TM_SHA256SUM 31558b0dd7558d4660f09d90d3ef0739fc9d83fe2541e53b72ac3732599a8b49

RUN apk update && apk add --no-cache --virtual .build-deps \
        openssl \
        && \
    wget -qO /tmp/tendermint.zip https://github.com/tendermint/tendermint/releases/download/v${TM_DOWNLOAD_PATH}/tendermint_${TM_VERSION}_linux_amd64.zip && \
    echo "${TM_SHA256SUM}  /tmp/tendermint.zip" | sha256sum -c && \
    unzip -d /usr/bin /tmp/tendermint.zip && \
    rm -f tendermint.zip && \
    apk del .build-deps


FROM alpine:3.7
LABEL maintainer="NDID IT Team <it@ndid.co.th>"

# Tendermint will be looking for genesis file in /tendermint (unless you change
# `genesis_file` in config.toml). You can put your config.toml and private
# validator file into /tendermint.
#
# The /tendermint/data dir is used by tendermint to store state.
ENV TMHOME /tendermint

# Set umask to 027
RUN umask 027 && echo "umask 0027" >> /etc/profile

COPY --from=build /var/cache/apk /var/cache/apk

# jq and curl used for extracting `pub_key` from private validator while
# deploying tendermint with Kubernetes. It is nice to have bash so the users
# could execute bash commands.
RUN apk update && apk add --no-cache bash curl jq && rm -rf /var/cache/apk

COPY --from=build /usr/bin/tendermint /usr/bin/tendermint
COPY docker/start-node.sh /usr/bin/
RUN mkdir -p ${TMHOME}

# Change owner to nobodoy:nogroup and permission to 640
RUN chown -R nobody:nogroup /usr/bin/start-node.sh /usr/bin/tendermint ${TMHOME}
RUN chmod -R 740 /usr/bin/start-node.sh /usr/bin/tendermint ${TMHOME}

USER nobody
ENTRYPOINT ["start-node.sh"]
STOPSIGNAL SIGTERM